environment = "DEVELOPMENT"
debug = false
grpcport = "8090"
httpport = "8080"
maxapiworker = 25

[workerqueue]
retries = 3
basedelay = 1

[cron]
time = "@every 1h"

[log]
customtimeformat = "2006-01-02T15:04:05.999999999Z07:00"
loglevel = -1

[grpcservers]
apikey = "12345678"
timeout = 10

[grpcservers.Address]
product = "svc-optisam-product-dev.dev-optisam.svc:8090"

[httpservers.Address]
auth = "svc-optisam-auth-dev.dev-optisam.svc:80"

[instrumentation]
addr = ":8081"

[instrumentation.prometheus]
enabled = true


[instrumentation.jaeger]
enabled = true
serviceName = "application-service"
collectorEndpoint = "http://jaeger-collector.dev-optisam.svc:14268/api/traces"
agentEndpoint = "jaeger-agent.dev-optisam.svc:6831"
# username = ""
# password = ""

[dgraph]
hosts = [
    "svc-optisam-dgraph.dev-optisam.svc:9080"
]

[database]
host = "svc-optisam-postgres.dev-optisam.svc"
port = 5432
user = "optisam"
#pass = ""
name = "application"

[app.params]
pageSize = 20
pageNum = 1
sortOrder = "asc"
sortBy = "name"

[iam]
publickeypath = "/opt/secret/ssh-privatekey"
apiKey = "12345678"
regopath = "rbac.rego"

[application]
#usernameadmin = ""
#passwordadmin = ""
#usernamesuperadmin = ""
#passwordsuperadmin = ""
#usernameuser = ""
#passworduser = ""