environment = "development"
debug = false
grpcport = "5083"
httpport = "6083"

[log]
customtimeformat = "2006-01-02T15:04:05.999999999Z07:00"
loglevel = 0

[instrumentation]
addr = ":8092"

[instrumentation.prometheus]
enabled = false

[instrumentation.jaeger]
enabled = false
collectorEndpoint = "http://localhost:14268/api/traces"
agentEndpoint = "localhost:6831"
# username = ""
# password = ""

[dgraph]
hosts = [
    "dgraph:9080"
]

[database]
host = "postgres"
port = 5432
user = "optisam"
pass = "optisam"
name = "application"

[app.params]
pageSize = 20
pageNum = 1
sortOrder = "asc"
sortBy = "name"

[iam]
publickeypath = "cert.pem"
apiKey = "12345678"
regopath = "rbac.rego"
