// Copyright (C) 2019 Orange
// 
// This software is distributed under the terms and conditions of the 'Apache License 2.0'
// license which can be found in the file 'License.txt' in this package distribution 
// or at 'http://www.apache.org/licenses/LICENSE-2.0'. 

// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	GetApplicationInstance(ctx context.Context, instanceID string) (ApplicationsInstance, error)
	GetApplicationsView(ctx context.Context, arg GetApplicationsViewParams) ([]GetApplicationsViewRow, error)
	GetInstancesView(ctx context.Context, arg GetInstancesViewParams) ([]GetInstancesViewRow, error)
	UpsertApplication(ctx context.Context, arg UpsertApplicationParams) error
	UpsertApplicationInstance(ctx context.Context, arg UpsertApplicationInstanceParams) error
}

var _ Querier = (*Queries)(nil)
