skeleton_scope = "../skeletonscope"
data_dir = "../testdata"
badger_dir = "mapping_badger"
schema_dir = "../schema"
batch_size = 1000
zero = "localhost:5080"
alpha = [
    "localhost:9080"
   # "localhost:9081"
]