kind: "Template"
apiVersion: "v1"
metadata:
  name: "deploy-template"
  annotations:
    description: "Template for deployment"
objects:
  - kind: CronJob
    apiVersion: batch/v1beta1
    metadata:
      name: optisam-dataloader-cronjob
    spec:
      schedule: "0 */1 * * *"  
      jobTemplate:             
        spec:
          backoffLimit: 1
          template:
            metadata:
              labels:          
                parent: "cronjob"
            spec:
              restartPolicy: Never
              containers:
                - name: optisam-dataloader-cronjob
                  image: ${DOCKER_REGISTRY}/optisam/dataloader-service:${TAG}
                  imagePullPolicy: Always
                  command: ["/bin/sh","-c"]
                  args: ["pwd; ls; 
                  ./dataloader staticdata --config=/opt/config/config-${ENV}.toml;
                   ./dataloader equipments --config=/opt/config/config-${ENV}.toml; "]
                  env:
                    - name: "ENV"
                      value: ${ENV}
                  volumeMounts:
                    - name: optisam-data
                      mountPath: /optisam_dir
                    - name: config-volume
                      mountPath: /opt/config
                  resources:
                    requests:
                      cpu: "400m"
                      memory: "600Mi"
                    limits:
                      cpu: "400m"
                      memory: "600Mi"
              volumes:
                - name: optisam-data
                  persistentVolumeClaim:
                    claimName: optisam-storage
                - name: config-volume
                  configMap:
                    name: config-dataloader-${ENV}
              
parameters:
  - name: TAG
    description: Tag for Docker image
    required: true
    value: latest
  - name: ENV
    description: Env for deployment
    required: true
  - name: DOCKER_REGISTRY
    description: Artifactory URL to download images
    required: true