FROM dockerproxy-iva.si.francetelecom.fr/alpine:latest
LABEL name="OPISAM" \
    description="Optisam License Service" \
    authors="Dharmjit Singh, Shweta Singh" \
    maintainer="Dharmjit Singh <dharmjit.singh@orange.com>" \
    url="https://gitlab.forge.orange-labs.fr/optisam/optisam-backend.git"

WORKDIR /opt/application/
COPY ${CI_PROJECT_DIR}/license_service/bin/ /opt/application/
COPY license-service/cmd/server/cert.pem/ /opt/application/
EXPOSE 8080
ENTRYPOINT ./server