version: "3.2"

services:
  db:
    image: optisam/postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=optisam
      - POSTGRES_USER=optisam
      - POSTGRES_PASSWORD=optisam
  optisam-auth-service:
    image: optisam/auth-service
    restart: always
    ports:
      - "9091:9091"
    depends_on:
      - db 
  optisam-account-service:
    image: optisam/account-service
    restart: always
    ports:
      - "9093:9093"
    depends_on:
      - db 
  optisam-license-service:
    image: optisam/license-service 
    restart: always
    ports:
      - "8091:8091"
    depends_on:
      - alpha 
  zero:
    image: optisam/dgraph:latest
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080  
  alpha:
    image: optisam/dgraph:latest
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=server:7080 --lru_mb=2048 --zero=zero:5080
  ratel:
    image: optisam/dgraph:latest
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 8000:8000
    command: dgraph-ratel
  
volumes:
  dgraph: