FROM dockerproxy-iva.si.francetelecom.fr/alpine:latest

LABEL name="OPTISAM" \
    description="Optisam Dataloader Service" \
    authors="Dharmjit Singh, Vijay Kumar" \
    maintainer="Dharmjit Singh <dharmjit.singh@orange.com>" \
    url="https://gitlab.forge.orange-labs.fr/optisam/optisam-backend.git"

WORKDIR /opt/application/
COPY ${CI_PROJECT_DIR}/dataloader_service/bin/ /opt/application/ 
COPY license-service/cmd/server/cert.pem/ /opt/application/ 
COPY license-service/pkg/repository/v1/dgraph/schema /opt/application/schema 
COPY license-service/pkg/repository/v1/dgraph/skeletonscope /opt/application/skeletonscope

ENTRYPOINT ./dataloader
