FROM dockerproxy-iva.si.francetelecom.fr/alpine:latest
LABEL name="OPISAM" \
    description="Optisam Auth Service" \
    authors="Dharmjit Singh, Vijay Kumar" \
    maintainer="Dharmjit Singh <dharmjit.singh@orange.com>" \
    url="https://gitlab.forge.orange-labs.fr/optisam/optisam-backend.git"

WORKDIR /opt/application/
COPY ${CI_PROJECT_DIR}/auth_service/bin/ /opt/application/
COPY auth-service/cmd/server/cert.pem/ /opt/application/
COPY auth-service/cmd/server/key.pem/ /opt/application/

EXPOSE 8080
ENTRYPOINT ./server
