version: "3.2"

services:
  db:
    image: optisam/postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=optisam
      - POSTGRES_USER=optisam
      - POSTGRES_PASSWORD=optisam
  optisam-auth-service:
    image: optisam/auth-service
    restart: always
    ports:
      - "8091:8090"
    depends_on:
      - db 
  optisam-account-service:
    image: optisam/account-service
    restart: always
    ports:
      - "8092:8090"
    depends_on:
      - db 
  optisam-license-service:
    image: optisam/license-service 
    restart: always
    ports:
      - "8093:8090"
    depends_on:
      - dgraph 
  optisam-import-service:
    image: optisam/import-service 
    restart: always
    ports:
      - "8094:8090"
    depends_on:
      - db
  optisam-ui-service:
    image: optisam/ui-service
    restart: always
    ports:
      - "8090:8080"
  dgraph:
    image: optisam/dgraph:latest
    restart: on-failure
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 8000:8000
      - 8080:8080
      - 9080:9080

volumes:
  dgraph: