environment = "development"
debug = true
grpcport = "12090"
httpport = "12091"
maxapiworker = 25
DashboardTimeZone = "CET"
DgraphBatchSize = 70
NoOfPartitions = 1

[workerqueue]
retries = 0
basedelay = 1

[log]
customtimeformat = "2006-01-02T15:04:05.999999999Z07:00"
loglevel = -1

[instrumentation]
addr = ":8092"

[instrumentation.prometheus]
enabled = false

[instrumentation.jaeger]
enabled = false
collectorEndpoint = "http://192.168.99.100:14268/api/traces"
agentEndpoint = "192.168.99.100:6831"
# username = ""
# password = ""

[dgraph]
hosts = [
   # "https://green-feather-500064.ap-south-1.aws.cloud.dgraph.io"
#    "10.171.44.163:9082"  dev dgrpah
    "127.0.0.1:9080"

]

[database]
host = "localhost"
port = 5431
# should be user of full rights
[database.admin]
user = "optisam"
pass = "samopti@19"
name = "product" 

# user of inser/update/delete/read access
[database.user]
user = "optisam_app_user"
pass = "s@cr@t!23"
name = "product"

[database.migration]
version = "1.4_schema.sql;1.4.3_schema.sql;1.4.2_schema.sql"
direction = "up"
migrationPath  = "./../../pkg/repository/v1/postgres/schema"
deleteMigrations = true

[redis]
host = "localhost:6379"
pass = ""
db = 0
username = ""

[app.params]
pageSize = 20
pageNum = 1
sortOrder = "asc"
sortBy = "name"

[iam]
publickeypath = "cert.pem"
apiKey = "12345678"
regopath = "rbac.rego"

[cron]
time = "@midnight"

[grpcservers]
apikey = "12345678"
timeout = 10

[grpcservers.Address]
license = "localhost:19091"
metric = "localhost:18090"
application = "localhost:11090"
account = "localhost:20000"
equipment = "localhost:14090"
notification = "localhost:15000"

[httpservers.Address]
auth = "localhost:9097"

[application]
#usernameadmin = ""
#passwordadmin = ""
#usernamesuperadmin = ""
#passwordsuperadmin = ""
#usernameuser = ""
#passworduser = ""


[emailtemplate]
expiringSoonPath = "./../../pkg/worker/templates/expiringSoonMaintenance.html"
expiredPath = "./../../pkg/worker/templates/expiredMaintenance.html"
	
[kafka]
bootstrapservers = "dev-kafka-externel-bootstrap-dev-optisam.apps.fr01.paas.tech.orange:443"
securityprotocol = "ssl"
sslkeylocation = "client.key.pem"
sslcertificatelocation = "client.crt.pem"
sslcalocation = "ca.crt.pem"