environment = "DEVELOPMENT"
debug = false
grpcport = "8090"
httpport = "8080"
maxapiworker = 25

# ./schema
MigrationPath  = "./schema"

[workerqueue]
retries = 3
basedelay = 1

[cron]
time = "@every 12h"

[log]
customtimeformat = "2006-01-02T15:04:05.999999999Z07:00"
loglevel = -1

[instrumentation]
addr = ":8081"

[instrumentation.prometheus]
enabled = true


[instrumentation.jaeger]
enabled = true
serviceName = "product-service"
collectorEndpoint = "http://jaeger-collector.dev-optisam.svc:14268/api/traces"
agentEndpoint = "jaeger-agent.dev-optisam.svc:6831"
# username = ""
# password = ""

[dgraph]
hosts = [
    "svc-optisam-dgraph.dev-optisam.svc:9080"
]


[database]
host = "svc-optisam-postgres.dev-optisam.svc"
port = 5432
[database.admin]
user = "optisam"
pass = ""
name = "product" 

# user of inser/update/delete/read access
[database.user]
user = "optisam_app_user"
pass = ""
name = "product" 
[database.Migration]
version = ""
direction = "up"
migrationPath  = "./schema"

[app.params]
pageSize = 20
pageNum = 1
sortOrder = "asc"
sortBy = "name"

[iam]
publickeypath = "/opt/secret/ssh-privatekey"
apiKey = "12345678"
regopath = "rbac.rego"

[grpcservers]
apikey = "12345678"
timeout = 10

[grpcservers.Address]
license = "svc-optisam-license-pc.dev-optisam.svc:8090"
metric = "svc-optisam-metric-pc.dev-optisam.svc:8090"
application = "svc-optisam-application-pc.dev-optisam.svc:8090"
account = "svc-optisam-account-pc.dev-optisam.svc:8090"
equipment = "svc-optisam-equipment-pc.dev-optisam.svc:8090"

[httpservers.Address]
auth = "svc-optisam-auth-pc.dev-optisam.svc:80"

[application]
#usernameadmin = ""
#passwordadmin = ""
#usernamesuperadmin = ""
#passwordsuperadmin = ""
#usernameuser = ""
#passworduser = ""
