environment = "development"
debug = false
grpcport = "12090"
httpport = "12091"
maxapiworker = 25
DashboardTimeZone = "CET"

[workerqueue]
retries = 0
basedelay = 1

[log]
customtimeformat = "2006-01-02T15:04:05.999999999Z07:00"
loglevel = -1

[instrumentation]
addr = ":8092"

[instrumentation.prometheus]
enabled = false

[instrumentation.jaeger]
enabled = false
collectorEndpoint = "http://192.168.99.100:14268/api/traces"
agentEndpoint = "192.168.99.100:6831"
# username = ""
# password = ""

[dgraph]
hosts = [
    "localhost:9080"
#    "10.171.44.163:9082"  dev dgrpah

]

[database]
host = "localhost"
port = 5432
user = "optisam"
pass = "optisam"
name = "optisam"

[app.params]
pageSize = 20
pageNum = 1
sortOrder = "asc"
sortBy = "name"

[iam]
publickeypath = "cert.pem"
apiKey = "12345678"
regopath = "rbac.rego"

[cron]
time = "@midnight"

[grpcservers]
apikey = "12345678"
timeout = 10

[grpcservers.Address]
license = "localhost:19091"
metric = "localhost:18090"
application = "localhost:11090"
account = "localhost:20000"
equipment = "localhost:14090"

[httpservers.Address]
auth = "localhost:9093"
