// Copyright (C) 2019 Orange
// 
// This software is distributed under the terms and conditions of the 'Apache License 2.0'
// license which can be found in the file 'License.txt' in this package distribution 
// or at 'http://www.apache.org/licenses/LICENSE-2.0'. 

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: equipment.proto

package v1

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SortOrder int32

const (
	SortOrder_ASC  SortOrder = 0
	SortOrder_asc  SortOrder = 0
	SortOrder_DESC SortOrder = 1
	SortOrder_desc SortOrder = 1
)

var SortOrder_name = map[int32]string{
	0: "ASC",
	// Duplicate value: 0: "asc",
	1: "DESC",
	// Duplicate value: 1: "desc",
}

var SortOrder_value = map[string]int32{
	"ASC":  0,
	"asc":  0,
	"DESC": 1,
	"desc": 1,
}

func (x SortOrder) String() string {
	return proto.EnumName(SortOrder_name, int32(x))
}

func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dbcd82406809d9b8, []int{0}
}

type DataTypes int32

const (
	DataTypes_UNKNOWN DataTypes = 0
	DataTypes_STRING  DataTypes = 1
	DataTypes_INT     DataTypes = 2
	DataTypes_FLOAT   DataTypes = 3
)

var DataTypes_name = map[int32]string{
	0: "UNKNOWN",
	1: "STRING",
	2: "INT",
	3: "FLOAT",
}

var DataTypes_value = map[string]int32{
	"UNKNOWN": 0,
	"STRING":  1,
	"INT":     2,
	"FLOAT":   3,
}

func (x DataTypes) String() string {
	return proto.EnumName(DataTypes_name, int32(x))
}

func (DataTypes) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dbcd82406809d9b8, []int{1}
}

type EquipmentMetadataRequest_Attributes int32

const (
	EquipmentMetadataRequest_All      EquipmentMetadataRequest_Attributes = 0
	EquipmentMetadataRequest_Mapped   EquipmentMetadataRequest_Attributes = 1
	EquipmentMetadataRequest_Unmapped EquipmentMetadataRequest_Attributes = 2
)

var EquipmentMetadataRequest_Attributes_name = map[int32]string{
	0: "All",
	1: "Mapped",
	2: "Unmapped",
}

var EquipmentMetadataRequest_Attributes_value = map[string]int32{
	"All":      0,
	"Mapped":   1,
	"Unmapped": 2,
}

func (x EquipmentMetadataRequest_Attributes) String() string {
	return proto.EnumName(EquipmentMetadataRequest_Attributes_name, int32(x))
}

func (EquipmentMetadataRequest_Attributes) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dbcd82406809d9b8, []int{15, 0}
}

type ListEquipmentMetadataRequest_Type int32

const (
	ListEquipmentMetadataRequest_UN_MAPPED ListEquipmentMetadataRequest_Type = 0
	ListEquipmentMetadataRequest_MAPPED    ListEquipmentMetadataRequest_Type = 1
	ListEquipmentMetadataRequest_ALL       ListEquipmentMetadataRequest_Type = 2
)

var ListEquipmentMetadataRequest_Type_name = map[int32]string{
	0: "UN_MAPPED",
	1: "MAPPED",
	2: "ALL",
}

var ListEquipmentMetadataRequest_Type_value = map[string]int32{
	"UN_MAPPED": 0,
	"MAPPED":    1,
	"ALL":       2,
}

func (x ListEquipmentMetadataRequest_Type) String() string {
	return proto.EnumName(ListEquipmentMetadataRequest_Type_name, int32(x))
}

func (ListEquipmentMetadataRequest_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dbcd82406809d9b8, []int{16, 0}
}

type StringFilter_Type int32

const (
	StringFilter_REGEX StringFilter_Type = 0
	StringFilter_EQ    StringFilter_Type = 1
)

var StringFilter_Type_name = map[int32]string{
	0: "REGEX",
	1: "EQ",
}

var StringFilter_Type_value = map[string]int32{
	"REGEX": 0,
	"EQ":    1,
}

func (x StringFilter_Type) String() string {
	return proto.EnumName(StringFilter_Type_name, int32(x))
}

func (StringFilter_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dbcd82406809d9b8, []int{23, 0}
}

type UpsertMetadataRequest struct {
	MetadataType         string   `protobuf:"bytes,1,opt,name=metadata_type,json=metadataType,proto3" json:"metadata_type,omitempty"`
	MetadataSource       string   `protobuf:"bytes,2,opt,name=metadata_source,json=metadataSource,proto3" json:"metadata_source,omitempty"`
	MetadataAttributes   []string `protobuf:"bytes,3,rep,name=metadata_attributes,json=metadataAttributes,proto3" json:"metadata_attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpsertMetadataRequest) Reset()         { *m = UpsertMetadataRequest{} }
func (m *UpsertMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*UpsertMetadataRequest) ProtoMessage()    {}
func (*UpsertMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbcd82406809d9b8, []int{0}
}

func (m *UpsertMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertMetadataRequest.Unmarshal(m, b)
}
func (m *UpsertMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertMetadataRequest.Marshal(b, m, deterministic)
}
func (m *UpsertMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertMetadataRequest.Merge(m, src)
}
func (m *UpsertMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_UpsertMetadataRequest.Size(m)
}
func (m *UpsertMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertMetadataRequest proto.InternalMessageInfo

func (m *UpsertMetadataRequest) GetMetadataType() string {
	if m != nil {
		return m.MetadataType
	}
	return ""
}

func (m *UpsertMetadataRequest) GetMetadataSource() string {
	if m != nil {
		return m.MetadataSource
	}
	return ""
}

func (m *UpsertMetadataRequest) GetMetadataAttributes() []string {
	if m != nil {
		return m.MetadataAttributes
	}
	return nil
}

type UpsertMetadataResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpsertMetadataResponse) Reset()         { *m = UpsertMetadataResponse{} }
func (m *UpsertMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*UpsertMetadataResponse) ProtoMessage()    {}
func (*UpsertMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbcd82406809d9b8, []int{1}
}

func (m *UpsertMetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertMetadataResponse.Unmarshal(m, b)
}
func (m *UpsertMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertMetadataResponse.Marshal(b, m, deterministic)
}
func (m *UpsertMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertMetadataResponse.Merge(m, src)
}
func (m *UpsertMetadataResponse) XXX_Size() int {
	return xxx_messageInfo_UpsertMetadataResponse.Size(m)
}
func (m *UpsertMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertMetadataResponse proto.InternalMessageInfo

func (m *UpsertMetadataResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type UpsertEquipmentRequest struct {
	Scope                string          `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	EqType               string          `protobuf:"bytes,2,opt,name=eq_type,json=eqType,proto3" json:"eq_type,omitempty"`
	EqData               *_struct.Struct `protobuf:"bytes,3,opt,name=eq_data,json=eqData,proto3" json:"eq_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpsertEquipmentRequest) Reset()         { *m = UpsertEquipmentRequest{} }
func (m *UpsertEquipmentRequest) String() string { return proto.CompactTextString(m) }
func (*UpsertEquipmentRequest) ProtoMessage()    {}
func (*UpsertEquipmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbcd82406809d9b8, []int{2}
}

func (m *UpsertEquipmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertEquipmentRequest.Unmarshal(m, b)
}
func (m *UpsertEquipmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertEquipmentRequest.Marshal(b, m, deterministic)
}
func (m *UpsertEquipmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertEquipmentRequest.Merge(m, src)
}
func (m *UpsertEquipmentRequest) XXX_Size() int {
	return xxx_messageInfo_UpsertEquipmentRequest.Size(m)
}
func (m *UpsertEquipmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertEquipmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertEquipmentRequest proto.InternalMessageInfo

func (m *UpsertEquipmentRequest) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *UpsertEquipmentRequest) GetEqType() string {
	if m != nil {
		return m.EqType
	}
	return ""
}

func (m *UpsertEquipmentRequest) GetEqData() *_struct.Struct {
	if m != nil {
		return m.EqData
	}
	return nil
}

type UpsertEquipmentResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpsertEquipmentResponse) Reset()         { *m = UpsertEquipmentResponse{} }
func (m *UpsertEquipmentResponse) String() string { return proto.CompactTextString(m) }
func (*UpsertEquipmentResponse) ProtoMessage()    {}
func (*UpsertEquipmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbcd82406809d9b8, []int{3}
}

func (m *UpsertEquipmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertEquipmentResponse.Unmarshal(m, b)
}
func (m *UpsertEquipmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertEquipmentResponse.Marshal(b, m, deterministic)
}
func (m *UpsertEquipmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertEquipmentResponse.Merge(m, src)
}
func (m *UpsertEquipmentResponse) XXX_Size() int {
	return xxx_messageInfo_UpsertEquipmentResponse.Size(m)
}
func (m *UpsertEquipmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertEquipmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertEquipmentResponse proto.InternalMessageInfo

func (m *UpsertEquipmentResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ListEquipmentsForProductAggregationRequest struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EqTypeId             string    `protobuf:"bytes,2,opt,name=eq_type_id,json=eqTypeId,proto3" json:"eq_type_id,omitempty"`
	PageNum              int32     `protobuf:"varint,3,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize             int32     `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBy               string    `protobuf:"bytes,5,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder            SortOrder `protobuf:"varint,6,opt,name=sort_order,json=sortOrder,proto3,enum=v1.SortOrder" json:"sort_order,omitempty"`
	SearchParams         string    `protobuf:"bytes,7,opt,name=search_params,json=searchParams,proto3" json:"search_params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListEquipmentsForProductAggregationRequest) Reset() {
	*m = ListEquipmentsForProductAggregationRequest{}
}
func (m *ListEquipmentsForProductAggregationRequest) String() string {
	return proto.CompactTextString(m)
}
func (*ListEquipmentsForProductAggregationRequest) ProtoMessage() {}
func (*ListEquipmentsForProductAggregationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbcd82406809d9b8, []int{4}
}

func (m *ListEquipmentsForProductAggregationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEquipmentsForProductAggregationRequest.Unmarshal(m, b)
}
func (m *ListEquipmentsForProductAggregationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEquipmentsForProductAggregationRequest.Marshal(b, m, deterministic)
}
func (m *ListEquipmentsForProductAggregationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEquipmentsForProductAggregationRequest.Merge(m, src)
}
func (m *ListEquipmentsForProductAggregationRequest) XXX_Size() int {
	return xxx_messageInfo_ListEquipmentsForProductAggregationRequest.Size(m)
}
func (m *ListEquipmentsForProductAggregationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEquipmentsForProductAggregationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListEquipmentsForProductAggregationRequest proto.InternalMessageInfo

func (m *ListEquipmentsForProductAggregationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListEquipmentsForProductAggregationRequest) GetEqTypeId() string {
	if m != nil {
		return m.EqTypeId
	}
	return ""
}

func (m *ListEquipmentsForProductAggregationRequest) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *ListEquipmentsForProductAggregationRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListEquipmentsForProductAggregationRequest) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *ListEquipmentsForProductAggregationRequest) GetSortOrder() SortOrder {
	if m != nil {
		return m.SortOrder
	}
	return SortOrder_ASC
}

func (m *ListEquipmentsForProductAggregationRequest) GetSearchParams() string {
	if m != nil {
		return m.SearchParams
	}
	return ""
}

type ListEquipmentsForProductRequest struct {
	SwidTag              string    `protobuf:"bytes,1,opt,name=swid_tag,json=swidTag,proto3" json:"swid_tag,omitempty"`
	EqTypeId             string    `protobuf:"bytes,2,opt,name=eq_type_id,json=eqTypeId,proto3" json:"eq_type_id,omitempty"`
	PageNum              int32     `protobuf:"varint,3,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize             int32     `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBy               string    `protobuf:"bytes,5,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder            SortOrder `protobuf:"varint,6,opt,name=sort_order,json=sortOrder,proto3,enum=v1.SortOrder" json:"sort_order,omitempty"`
	SearchParams         string    `protobuf:"bytes,7,opt,name=search_params,json=searchParams,proto3" json:"search_params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListEquipmentsForProductRequest) Reset()         { *m = ListEquipmentsForProductRequest{} }
func (m *ListEquipmentsForProductRequest) String() string { return proto.CompactTextString(m) }
func (*ListEquipmentsForProductRequest) ProtoMessage()    {}
func (*ListEquipmentsForProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbcd82406809d9b8, []int{5}
}

func (m *ListEquipmentsForProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEquipmentsForProductRequest.Unmarshal(m, b)
}
func (m *ListEquipmentsForProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEquipmentsForProductRequest.Marshal(b, m, deterministic)
}
func (m *ListEquipmentsForProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEquipmentsForProductRequest.Merge(m, src)
}
func (m *ListEquipmentsForProductRequest) XXX_Size() int {
	return xxx_messageInfo_ListEquipmentsForProductRequest.Size(m)
}
func (m *ListEquipmentsForProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEquipmentsForProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListEquipmentsForProductRequest proto.InternalMessageInfo

func (m *ListEquipmentsForProductRequest) GetSwidTag() string {
	if m != nil {
		return m.SwidTag
	}
	return ""
}

func (m *ListEquipmentsForProductRequest) GetEqTypeId() string {
	if m != nil {
		return m.EqTypeId
	}
	return ""
}

func (m *ListEquipmentsForProductRequest) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *ListEquipmentsForProductRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListEquipmentsForProductRequest) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *ListEquipmentsForProductRequest) GetSortOrder() SortOrder {
	if m != nil {
		return m.SortOrder
	}
	return SortOrder_ASC
}

func (m *ListEquipmentsForProductRequest) GetSearchParams() string {
	if m != nil {
		return m.SearchParams
	}
	return ""
}

type ListEquipmentChildrenRequest struct {
	TypeId               string    `protobuf:"bytes,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	EquipId              string    `protobuf:"bytes,2,opt,name=equip_id,json=equipId,proto3" json:"equip_id,omitempty"`
	ChildrenTypeId       string    `protobuf:"bytes,3,opt,name=children_type_id,json=childrenTypeId,proto3" json:"children_type_id,omitempty"`
	PageNum              int32     `protobuf:"varint,4,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize             int32     `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBy               string    `protobuf:"bytes,6,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder            SortOrder `protobuf:"varint,7,opt,name=sort_order,json=sortOrder,proto3,enum=v1.SortOrder" json:"sort_order,omitempty"`
	SearchParams         string    `protobuf:"bytes,8,opt,name=search_params,json=searchParams,proto3" json:"search_params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListEquipmentChildrenRequest) Reset()         { *m = ListEquipmentChildrenRequest{} }
func (m *ListEquipmentChildrenRequest) String() string { return proto.CompactTextString(m) }
func (*ListEquipmentChildrenRequest) ProtoMessage()    {}
func (*ListEquipmentChildrenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbcd82406809d9b8, []int{6}
}

func (m *ListEquipmentChildrenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEquipmentChildrenRequest.Unmarshal(m, b)
}
func (m *ListEquipmentChildrenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEquipmentChildrenRequest.Marshal(b, m, deterministic)
}
func (m *ListEquipmentChildrenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEquipmentChildrenRequest.Merge(m, src)
}
func (m *ListEquipmentChildrenRequest) XXX_Size() int {
	return xxx_messageInfo_ListEquipmentChildrenRequest.Size(m)
}
func (m *ListEquipmentChildrenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEquipmentChildrenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListEquipmentChildrenRequest proto.InternalMessageInfo

func (m *ListEquipmentChildrenRequest) GetTypeId() string {
	if m != nil {
		return m.TypeId
	}
	return ""
}

func (m *ListEquipmentChildrenRequest) GetEquipId() string {
	if m != nil {
		return m.EquipId
	}
	return ""
}

func (m *ListEquipmentChildrenRequest) GetChildrenTypeId() string {
	if m != nil {
		return m.ChildrenTypeId
	}
	return ""
}

func (m *ListEquipmentChildrenRequest) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *ListEquipmentChildrenRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListEquipmentChildrenRequest) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *ListEquipmentChildrenRequest) GetSortOrder() SortOrder {
	if m != nil {
		return m.SortOrder
	}
	return SortOrder_ASC
}

func (m *ListEquipmentChildrenRequest) GetSearchParams() string {
	if m != nil {
		return m.SearchParams
	}
	return ""
}

type ListEquipmentParentsRequest struct {
	TypeId               string   `protobuf:"bytes,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	EquipId              string   `protobuf:"bytes,2,opt,name=equip_id,json=equipId,proto3" json:"equip_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEquipmentParentsRequest) Reset()         { *m = ListEquipmentParentsRequest{} }
func (m *ListEquipmentParentsRequest) String() string { return proto.CompactTextString(m) }
func (*ListEquipmentParentsRequest) ProtoMessage()    {}
func (*ListEquipmentParentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbcd82406809d9b8, []int{7}
}

func (m *ListEquipmentParentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEquipmentParentsRequest.Unmarshal(m, b)
}
func (m *ListEquipmentParentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEquipmentParentsRequest.Marshal(b, m, deterministic)
}
func (m *ListEquipmentParentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEquipmentParentsRequest.Merge(m, src)
}
func (m *ListEquipmentParentsRequest) XXX_Size() int {
	return xxx_messageInfo_ListEquipmentParentsRequest.Size(m)
}
func (m *ListEquipmentParentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEquipmentParentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListEquipmentParentsRequest proto.InternalMessageInfo

func (m *ListEquipmentParentsRequest) GetTypeId() string {
	if m != nil {
		return m.TypeId
	}
	return ""
}

func (m *ListEquipmentParentsRequest) GetEquipId() string {
	if m != nil {
		return m.EquipId
	}
	return ""
}

type GetEquipmentParentsResponse struct {
	Equipments           string   `protobuf:"bytes,1,opt,name=equipments,proto3" json:"equipments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEquipmentParentsResponse) Reset()         { *m = GetEquipmentParentsResponse{} }
func (m *GetEquipmentParentsResponse) String() string { return proto.CompactTextString(m) }
func (*GetEquipmentParentsResponse) ProtoMessage()    {}
func (*GetEquipmentParentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbcd82406809d9b8, []int{8}
}

func (m *GetEquipmentParentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEquipmentParentsResponse.Unmarshal(m, b)
}
func (m *GetEquipmentParentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEquipmentParentsResponse.Marshal(b, m, deterministic)
}
func (m *GetEquipmentParentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEquipmentParentsResponse.Merge(m, src)
}
func (m *GetEquipmentParentsResponse) XXX_Size() int {
	return xxx_messageInfo_GetEquipmentParentsResponse.Size(m)
}
func (m *GetEquipmentParentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEquipmentParentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEquipmentParentsResponse proto.InternalMessageInfo

func (m *GetEquipmentParentsResponse) GetEquipments() string {
	if m != nil {
		return m.Equipments
	}
	return ""
}

type GetEquipmentRequest struct {
	TypeId               string   `protobuf:"bytes,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	EquipId              string   `protobuf:"bytes,2,opt,name=equip_id,json=equipId,proto3" json:"equip_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEquipmentRequest) Reset()         { *m = GetEquipmentRequest{} }
func (m *GetEquipmentRequest) String() string { return proto.CompactTextString(m) }
func (*GetEquipmentRequest) ProtoMessage()    {}
func (*GetEquipmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbcd82406809d9b8, []int{9}
}

func (m *GetEquipmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEquipmentRequest.Unmarshal(m, b)
}
func (m *GetEquipmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEquipmentRequest.Marshal(b, m, deterministic)
}
func (m *GetEquipmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEquipmentRequest.Merge(m, src)
}
func (m *GetEquipmentRequest) XXX_Size() int {
	return xxx_messageInfo_GetEquipmentRequest.Size(m)
}
func (m *GetEquipmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEquipmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEquipmentRequest proto.InternalMessageInfo

func (m *GetEquipmentRequest) GetTypeId() string {
	if m != nil {
		return m.TypeId
	}
	return ""
}

func (m *GetEquipmentRequest) GetEquipId() string {
	if m != nil {
		return m.EquipId
	}
	return ""
}

type GetEquipmentResponse struct {
	Equipment            string   `protobuf:"bytes,1,opt,name=equipment,proto3" json:"equipment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEquipmentResponse) Reset()         { *m = GetEquipmentResponse{} }
func (m *GetEquipmentResponse) String() string { return proto.CompactTextString(m) }
func (*GetEquipmentResponse) ProtoMessage()    {}
func (*GetEquipmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbcd82406809d9b8, []int{10}
}

func (m *GetEquipmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEquipmentResponse.Unmarshal(m, b)
}
func (m *GetEquipmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEquipmentResponse.Marshal(b, m, deterministic)
}
func (m *GetEquipmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEquipmentResponse.Merge(m, src)
}
func (m *GetEquipmentResponse) XXX_Size() int {
	return xxx_messageInfo_GetEquipmentResponse.Size(m)
}
func (m *GetEquipmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEquipmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEquipmentResponse proto.InternalMessageInfo

func (m *GetEquipmentResponse) GetEquipment() string {
	if m != nil {
		return m.Equipment
	}
	return ""
}

type ListEquipmentsRequest struct {
	TypeId               string       `protobuf:"bytes,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	PageNum              int32        `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize             int32        `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBy               string       `protobuf:"bytes,4,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder            SortOrder    `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3,enum=v1.SortOrder" json:"sort_order,omitempty"`
	SearchParams         string       `protobuf:"bytes,6,opt,name=search_params,json=searchParams,proto3" json:"search_params,omitempty"`
	Filter               *EquipFilter `protobuf:"bytes,7,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListEquipmentsRequest) Reset()         { *m = ListEquipmentsRequest{} }
func (m *ListEquipmentsRequest) String() string { return proto.CompactTextString(m) }
func (*ListEquipmentsRequest) ProtoMessage()    {}
func (*ListEquipmentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbcd82406809d9b8, []int{11}
}

func (m *ListEquipmentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEquipmentsRequest.Unmarshal(m, b)
}
func (m *ListEquipmentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEquipmentsRequest.Marshal(b, m, deterministic)
}
func (m *ListEquipmentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEquipmentsRequest.Merge(m, src)
}
func (m *ListEquipmentsRequest) XXX_Size() int {
	return xxx_messageInfo_ListEquipmentsRequest.Size(m)
}
func (m *ListEquipmentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEquipmentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListEquipmentsRequest proto.InternalMessageInfo

func (m *ListEquipmentsRequest) GetTypeId() string {
	if m != nil {
		return m.TypeId
	}
	return ""
}

func (m *ListEquipmentsRequest) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *ListEquipmentsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListEquipmentsRequest) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *ListEquipmentsRequest) GetSortOrder() SortOrder {
	if m != nil {
		return m.SortOrder
	}
	return SortOrder_ASC
}

func (m *ListEquipmentsRequest) GetSearchParams() string {
	if m != nil {
		return m.SearchParams
	}
	return ""
}

func (m *ListEquipmentsRequest) GetFilter() *EquipFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type EquipFilter struct {
	ApplicationId        *StringFilter `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	ProductId            *StringFilter `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	InstanceId           *StringFilter `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *EquipFilter) Reset()         { *m = EquipFilter{} }
func (m *EquipFilter) String() string { return proto.CompactTextString(m) }
func (*EquipFilter) ProtoMessage()    {}
func (*EquipFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbcd82406809d9b8, []int{12}
}

func (m *EquipFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EquipFilter.Unmarshal(m, b)
}
func (m *EquipFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EquipFilter.Marshal(b, m, deterministic)
}
func (m *EquipFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EquipFilter.Merge(m, src)
}
func (m *EquipFilter) XXX_Size() int {
	return xxx_messageInfo_EquipFilter.Size(m)
}
func (m *EquipFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_EquipFilter.DiscardUnknown(m)
}

var xxx_messageInfo_EquipFilter proto.InternalMessageInfo

func (m *EquipFilter) GetApplicationId() *StringFilter {
	if m != nil {
		return m.ApplicationId
	}
	return nil
}

func (m *EquipFilter) GetProductId() *StringFilter {
	if m != nil {
		return m.ProductId
	}
	return nil
}

func (m *EquipFilter) GetInstanceId() *StringFilter {
	if m != nil {
		return m.InstanceId
	}
	return nil
}

type ListEquipmentsResponse struct {
	TotalRecords         int32    `protobuf:"varint,1,opt,name=totalRecords,proto3" json:"totalRecords,omitempty"`
	Equipments           []byte   `protobuf:"bytes,2,opt,name=equipments,proto3" json:"equipments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEquipmentsResponse) Reset()         { *m = ListEquipmentsResponse{} }
func (m *ListEquipmentsResponse) String() string { return proto.CompactTextString(m) }
func (*ListEquipmentsResponse) ProtoMessage()    {}
func (*ListEquipmentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbcd82406809d9b8, []int{13}
}

func (m *ListEquipmentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEquipmentsResponse.Unmarshal(m, b)
}
func (m *ListEquipmentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEquipmentsResponse.Marshal(b, m, deterministic)
}
func (m *ListEquipmentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEquipmentsResponse.Merge(m, src)
}
func (m *ListEquipmentsResponse) XXX_Size() int {
	return xxx_messageInfo_ListEquipmentsResponse.Size(m)
}
func (m *ListEquipmentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEquipmentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListEquipmentsResponse proto.InternalMessageInfo

func (m *ListEquipmentsResponse) GetTotalRecords() int32 {
	if m != nil {
		return m.TotalRecords
	}
	return 0
}

func (m *ListEquipmentsResponse) GetEquipments() []byte {
	if m != nil {
		return m.Equipments
	}
	return nil
}

type UpdateEquipmentTypeRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Only send parent id if equipment type does not have a parent.
	ParentId             string       `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Attributes           []*Attribute `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdateEquipmentTypeRequest) Reset()         { *m = UpdateEquipmentTypeRequest{} }
func (m *UpdateEquipmentTypeRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateEquipmentTypeRequest) ProtoMessage()    {}
func (*UpdateEquipmentTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbcd82406809d9b8, []int{14}
}

func (m *UpdateEquipmentTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEquipmentTypeRequest.Unmarshal(m, b)
}
func (m *UpdateEquipmentTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEquipmentTypeRequest.Marshal(b, m, deterministic)
}
func (m *UpdateEquipmentTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEquipmentTypeRequest.Merge(m, src)
}
func (m *UpdateEquipmentTypeRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateEquipmentTypeRequest.Size(m)
}
func (m *UpdateEquipmentTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEquipmentTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEquipmentTypeRequest proto.InternalMessageInfo

func (m *UpdateEquipmentTypeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateEquipmentTypeRequest) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *UpdateEquipmentTypeRequest) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type EquipmentMetadataRequest struct {
	ID                   string                              `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Attributes           EquipmentMetadataRequest_Attributes `protobuf:"varint,2,opt,name=attributes,proto3,enum=v1.EquipmentMetadataRequest_Attributes" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *EquipmentMetadataRequest) Reset()         { *m = EquipmentMetadataRequest{} }
func (m *EquipmentMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*EquipmentMetadataRequest) ProtoMessage()    {}
func (*EquipmentMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbcd82406809d9b8, []int{15}
}

func (m *EquipmentMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EquipmentMetadataRequest.Unmarshal(m, b)
}
func (m *EquipmentMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EquipmentMetadataRequest.Marshal(b, m, deterministic)
}
func (m *EquipmentMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EquipmentMetadataRequest.Merge(m, src)
}
func (m *EquipmentMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_EquipmentMetadataRequest.Size(m)
}
func (m *EquipmentMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EquipmentMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EquipmentMetadataRequest proto.InternalMessageInfo

func (m *EquipmentMetadataRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *EquipmentMetadataRequest) GetAttributes() EquipmentMetadataRequest_Attributes {
	if m != nil {
		return m.Attributes
	}
	return EquipmentMetadataRequest_All
}

type ListEquipmentMetadataRequest struct {
	Type                 ListEquipmentMetadataRequest_Type `protobuf:"varint,1,opt,name=type,proto3,enum=v1.ListEquipmentMetadataRequest_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *ListEquipmentMetadataRequest) Reset()         { *m = ListEquipmentMetadataRequest{} }
func (m *ListEquipmentMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*ListEquipmentMetadataRequest) ProtoMessage()    {}
func (*ListEquipmentMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbcd82406809d9b8, []int{16}
}

func (m *ListEquipmentMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEquipmentMetadataRequest.Unmarshal(m, b)
}
func (m *ListEquipmentMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEquipmentMetadataRequest.Marshal(b, m, deterministic)
}
func (m *ListEquipmentMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEquipmentMetadataRequest.Merge(m, src)
}
func (m *ListEquipmentMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_ListEquipmentMetadataRequest.Size(m)
}
func (m *ListEquipmentMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEquipmentMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListEquipmentMetadataRequest proto.InternalMessageInfo

func (m *ListEquipmentMetadataRequest) GetType() ListEquipmentMetadataRequest_Type {
	if m != nil {
		return m.Type
	}
	return ListEquipmentMetadataRequest_UN_MAPPED
}

type ListEquipmentMetadataResponse struct {
	Metadata             []*EquipmentMetadata `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListEquipmentMetadataResponse) Reset()         { *m = ListEquipmentMetadataResponse{} }
func (m *ListEquipmentMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*ListEquipmentMetadataResponse) ProtoMessage()    {}
func (*ListEquipmentMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbcd82406809d9b8, []int{17}
}

func (m *ListEquipmentMetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEquipmentMetadataResponse.Unmarshal(m, b)
}
func (m *ListEquipmentMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEquipmentMetadataResponse.Marshal(b, m, deterministic)
}
func (m *ListEquipmentMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEquipmentMetadataResponse.Merge(m, src)
}
func (m *ListEquipmentMetadataResponse) XXX_Size() int {
	return xxx_messageInfo_ListEquipmentMetadataResponse.Size(m)
}
func (m *ListEquipmentMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEquipmentMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListEquipmentMetadataResponse proto.InternalMessageInfo

func (m *ListEquipmentMetadataResponse) GetMetadata() []*EquipmentMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type EquipmentMetadata struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Attributes           []string `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EquipmentMetadata) Reset()         { *m = EquipmentMetadata{} }
func (m *EquipmentMetadata) String() string { return proto.CompactTextString(m) }
func (*EquipmentMetadata) ProtoMessage()    {}
func (*EquipmentMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbcd82406809d9b8, []int{18}
}

func (m *EquipmentMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EquipmentMetadata.Unmarshal(m, b)
}
func (m *EquipmentMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EquipmentMetadata.Marshal(b, m, deterministic)
}
func (m *EquipmentMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EquipmentMetadata.Merge(m, src)
}
func (m *EquipmentMetadata) XXX_Size() int {
	return xxx_messageInfo_EquipmentMetadata.Size(m)
}
func (m *EquipmentMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_EquipmentMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_EquipmentMetadata proto.InternalMessageInfo

func (m *EquipmentMetadata) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *EquipmentMetadata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EquipmentMetadata) GetAttributes() []string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type EquipmentTypesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EquipmentTypesRequest) Reset()         { *m = EquipmentTypesRequest{} }
func (m *EquipmentTypesRequest) String() string { return proto.CompactTextString(m) }
func (*EquipmentTypesRequest) ProtoMessage()    {}
func (*EquipmentTypesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbcd82406809d9b8, []int{19}
}

func (m *EquipmentTypesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EquipmentTypesRequest.Unmarshal(m, b)
}
func (m *EquipmentTypesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EquipmentTypesRequest.Marshal(b, m, deterministic)
}
func (m *EquipmentTypesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EquipmentTypesRequest.Merge(m, src)
}
func (m *EquipmentTypesRequest) XXX_Size() int {
	return xxx_messageInfo_EquipmentTypesRequest.Size(m)
}
func (m *EquipmentTypesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EquipmentTypesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EquipmentTypesRequest proto.InternalMessageInfo

type EquipmentTypesResponse struct {
	EquipmentTypes       []*EquipmentType `protobuf:"bytes,1,rep,name=equipment_types,json=equipmentTypes,proto3" json:"equipment_types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *EquipmentTypesResponse) Reset()         { *m = EquipmentTypesResponse{} }
func (m *EquipmentTypesResponse) String() string { return proto.CompactTextString(m) }
func (*EquipmentTypesResponse) ProtoMessage()    {}
func (*EquipmentTypesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbcd82406809d9b8, []int{20}
}

func (m *EquipmentTypesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EquipmentTypesResponse.Unmarshal(m, b)
}
func (m *EquipmentTypesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EquipmentTypesResponse.Marshal(b, m, deterministic)
}
func (m *EquipmentTypesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EquipmentTypesResponse.Merge(m, src)
}
func (m *EquipmentTypesResponse) XXX_Size() int {
	return xxx_messageInfo_EquipmentTypesResponse.Size(m)
}
func (m *EquipmentTypesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EquipmentTypesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EquipmentTypesResponse proto.InternalMessageInfo

func (m *EquipmentTypesResponse) GetEquipmentTypes() []*EquipmentType {
	if m != nil {
		return m.EquipmentTypes
	}
	return nil
}

type EquipmentType struct {
	ID                   string       `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Type                 string       `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	ParentId             string       `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	ParentType           string       `protobuf:"bytes,4,opt,name=parent_type,json=parentType,proto3" json:"parent_type,omitempty"`
	MetadataId           string       `protobuf:"bytes,5,opt,name=metadata_id,json=metadataId,proto3" json:"metadata_id,omitempty"`
	MetadataSource       string       `protobuf:"bytes,6,opt,name=metadata_source,json=metadataSource,proto3" json:"metadata_source,omitempty"`
	Attributes           []*Attribute `protobuf:"bytes,7,rep,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EquipmentType) Reset()         { *m = EquipmentType{} }
func (m *EquipmentType) String() string { return proto.CompactTextString(m) }
func (*EquipmentType) ProtoMessage()    {}
func (*EquipmentType) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbcd82406809d9b8, []int{21}
}

func (m *EquipmentType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EquipmentType.Unmarshal(m, b)
}
func (m *EquipmentType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EquipmentType.Marshal(b, m, deterministic)
}
func (m *EquipmentType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EquipmentType.Merge(m, src)
}
func (m *EquipmentType) XXX_Size() int {
	return xxx_messageInfo_EquipmentType.Size(m)
}
func (m *EquipmentType) XXX_DiscardUnknown() {
	xxx_messageInfo_EquipmentType.DiscardUnknown(m)
}

var xxx_messageInfo_EquipmentType proto.InternalMessageInfo

func (m *EquipmentType) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *EquipmentType) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *EquipmentType) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *EquipmentType) GetParentType() string {
	if m != nil {
		return m.ParentType
	}
	return ""
}

func (m *EquipmentType) GetMetadataId() string {
	if m != nil {
		return m.MetadataId
	}
	return ""
}

func (m *EquipmentType) GetMetadataSource() string {
	if m != nil {
		return m.MetadataSource
	}
	return ""
}

func (m *EquipmentType) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type Attribute struct {
	ID               string    `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name             string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DataType         DataTypes `protobuf:"varint,3,opt,name=data_type,json=dataType,proto3,enum=v1.DataTypes" json:"data_type,omitempty"`
	PrimaryKey       bool      `protobuf:"varint,4,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	Displayed        bool      `protobuf:"varint,5,opt,name=displayed,proto3" json:"displayed,omitempty"`
	Searchable       bool      `protobuf:"varint,6,opt,name=searchable,proto3" json:"searchable,omitempty"`
	ParentIdentifier bool      `protobuf:"varint,7,opt,name=parent_identifier,json=parentIdentifier,proto3" json:"parent_identifier,omitempty"`
	MappedTo         string    `protobuf:"bytes,8,opt,name=mapped_to,json=mappedTo,proto3" json:"mapped_to,omitempty"`
	Simulated        bool      `protobuf:"varint,9,opt,name=simulated,proto3" json:"simulated,omitempty"`
	// Types that are valid to be assigned to Val:
	//	*Attribute_IntVal
	//	*Attribute_FloatVal
	//	*Attribute_StringVal
	Val isAttribute_Val `protobuf_oneof:"val"`
	// Types that are valid to be assigned to OldVal:
	//	*Attribute_IntValOld
	//	*Attribute_FloatValOld
	//	*Attribute_StringValOld
	OldVal               isAttribute_OldVal `protobuf_oneof:"old_val"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Attribute) Reset()         { *m = Attribute{} }
func (m *Attribute) String() string { return proto.CompactTextString(m) }
func (*Attribute) ProtoMessage()    {}
func (*Attribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbcd82406809d9b8, []int{22}
}

func (m *Attribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attribute.Unmarshal(m, b)
}
func (m *Attribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attribute.Marshal(b, m, deterministic)
}
func (m *Attribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attribute.Merge(m, src)
}
func (m *Attribute) XXX_Size() int {
	return xxx_messageInfo_Attribute.Size(m)
}
func (m *Attribute) XXX_DiscardUnknown() {
	xxx_messageInfo_Attribute.DiscardUnknown(m)
}

var xxx_messageInfo_Attribute proto.InternalMessageInfo

func (m *Attribute) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Attribute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Attribute) GetDataType() DataTypes {
	if m != nil {
		return m.DataType
	}
	return DataTypes_UNKNOWN
}

func (m *Attribute) GetPrimaryKey() bool {
	if m != nil {
		return m.PrimaryKey
	}
	return false
}

func (m *Attribute) GetDisplayed() bool {
	if m != nil {
		return m.Displayed
	}
	return false
}

func (m *Attribute) GetSearchable() bool {
	if m != nil {
		return m.Searchable
	}
	return false
}

func (m *Attribute) GetParentIdentifier() bool {
	if m != nil {
		return m.ParentIdentifier
	}
	return false
}

func (m *Attribute) GetMappedTo() string {
	if m != nil {
		return m.MappedTo
	}
	return ""
}

func (m *Attribute) GetSimulated() bool {
	if m != nil {
		return m.Simulated
	}
	return false
}

type isAttribute_Val interface {
	isAttribute_Val()
}

type Attribute_IntVal struct {
	IntVal int32 `protobuf:"varint,10,opt,name=int_val,json=intVal,proto3,oneof"`
}

type Attribute_FloatVal struct {
	FloatVal float32 `protobuf:"fixed32,11,opt,name=float_val,json=floatVal,proto3,oneof"`
}

type Attribute_StringVal struct {
	StringVal string `protobuf:"bytes,12,opt,name=string_val,json=stringVal,proto3,oneof"`
}

func (*Attribute_IntVal) isAttribute_Val() {}

func (*Attribute_FloatVal) isAttribute_Val() {}

func (*Attribute_StringVal) isAttribute_Val() {}

func (m *Attribute) GetVal() isAttribute_Val {
	if m != nil {
		return m.Val
	}
	return nil
}

func (m *Attribute) GetIntVal() int32 {
	if x, ok := m.GetVal().(*Attribute_IntVal); ok {
		return x.IntVal
	}
	return 0
}

func (m *Attribute) GetFloatVal() float32 {
	if x, ok := m.GetVal().(*Attribute_FloatVal); ok {
		return x.FloatVal
	}
	return 0
}

func (m *Attribute) GetStringVal() string {
	if x, ok := m.GetVal().(*Attribute_StringVal); ok {
		return x.StringVal
	}
	return ""
}

type isAttribute_OldVal interface {
	isAttribute_OldVal()
}

type Attribute_IntValOld struct {
	IntValOld int32 `protobuf:"varint,13,opt,name=int_val_old,json=intValOld,proto3,oneof"`
}

type Attribute_FloatValOld struct {
	FloatValOld float32 `protobuf:"fixed32,14,opt,name=float_val_old,json=floatValOld,proto3,oneof"`
}

type Attribute_StringValOld struct {
	StringValOld string `protobuf:"bytes,15,opt,name=string_val_old,json=stringValOld,proto3,oneof"`
}

func (*Attribute_IntValOld) isAttribute_OldVal() {}

func (*Attribute_FloatValOld) isAttribute_OldVal() {}

func (*Attribute_StringValOld) isAttribute_OldVal() {}

func (m *Attribute) GetOldVal() isAttribute_OldVal {
	if m != nil {
		return m.OldVal
	}
	return nil
}

func (m *Attribute) GetIntValOld() int32 {
	if x, ok := m.GetOldVal().(*Attribute_IntValOld); ok {
		return x.IntValOld
	}
	return 0
}

func (m *Attribute) GetFloatValOld() float32 {
	if x, ok := m.GetOldVal().(*Attribute_FloatValOld); ok {
		return x.FloatValOld
	}
	return 0
}

func (m *Attribute) GetStringValOld() string {
	if x, ok := m.GetOldVal().(*Attribute_StringValOld); ok {
		return x.StringValOld
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Attribute) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Attribute_IntVal)(nil),
		(*Attribute_FloatVal)(nil),
		(*Attribute_StringVal)(nil),
		(*Attribute_IntValOld)(nil),
		(*Attribute_FloatValOld)(nil),
		(*Attribute_StringValOld)(nil),
	}
}

type StringFilter struct {
	FilteringOrder       int32             `protobuf:"varint,1,opt,name=filteringOrder,proto3" json:"filteringOrder,omitempty"`
	Filteringkey         string            `protobuf:"bytes,2,opt,name=filteringkey,proto3" json:"filteringkey,omitempty"`
	FilterType           StringFilter_Type `protobuf:"varint,3,opt,name=filter_type,json=filterType,proto3,enum=v1.StringFilter_Type" json:"filter_type,omitempty"`
	FilteringkeyMultiple []string          `protobuf:"bytes,4,rep,name=filteringkey_multiple,json=filteringkeyMultiple,proto3" json:"filteringkey_multiple,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StringFilter) Reset()         { *m = StringFilter{} }
func (m *StringFilter) String() string { return proto.CompactTextString(m) }
func (*StringFilter) ProtoMessage()    {}
func (*StringFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbcd82406809d9b8, []int{23}
}

func (m *StringFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringFilter.Unmarshal(m, b)
}
func (m *StringFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringFilter.Marshal(b, m, deterministic)
}
func (m *StringFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringFilter.Merge(m, src)
}
func (m *StringFilter) XXX_Size() int {
	return xxx_messageInfo_StringFilter.Size(m)
}
func (m *StringFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_StringFilter.DiscardUnknown(m)
}

var xxx_messageInfo_StringFilter proto.InternalMessageInfo

func (m *StringFilter) GetFilteringOrder() int32 {
	if m != nil {
		return m.FilteringOrder
	}
	return 0
}

func (m *StringFilter) GetFilteringkey() string {
	if m != nil {
		return m.Filteringkey
	}
	return ""
}

func (m *StringFilter) GetFilterType() StringFilter_Type {
	if m != nil {
		return m.FilterType
	}
	return StringFilter_REGEX
}

func (m *StringFilter) GetFilteringkeyMultiple() []string {
	if m != nil {
		return m.FilteringkeyMultiple
	}
	return nil
}

func init() {
	proto.RegisterEnum("v1.SortOrder", SortOrder_name, SortOrder_value)
	proto.RegisterEnum("v1.DataTypes", DataTypes_name, DataTypes_value)
	proto.RegisterEnum("v1.EquipmentMetadataRequest_Attributes", EquipmentMetadataRequest_Attributes_name, EquipmentMetadataRequest_Attributes_value)
	proto.RegisterEnum("v1.ListEquipmentMetadataRequest_Type", ListEquipmentMetadataRequest_Type_name, ListEquipmentMetadataRequest_Type_value)
	proto.RegisterEnum("v1.StringFilter_Type", StringFilter_Type_name, StringFilter_Type_value)
	proto.RegisterType((*UpsertMetadataRequest)(nil), "v1.UpsertMetadataRequest")
	proto.RegisterType((*UpsertMetadataResponse)(nil), "v1.UpsertMetadataResponse")
	proto.RegisterType((*UpsertEquipmentRequest)(nil), "v1.UpsertEquipmentRequest")
	proto.RegisterType((*UpsertEquipmentResponse)(nil), "v1.UpsertEquipmentResponse")
	proto.RegisterType((*ListEquipmentsForProductAggregationRequest)(nil), "v1.ListEquipmentsForProductAggregationRequest")
	proto.RegisterType((*ListEquipmentsForProductRequest)(nil), "v1.ListEquipmentsForProductRequest")
	proto.RegisterType((*ListEquipmentChildrenRequest)(nil), "v1.ListEquipmentChildrenRequest")
	proto.RegisterType((*ListEquipmentParentsRequest)(nil), "v1.ListEquipmentParentsRequest")
	proto.RegisterType((*GetEquipmentParentsResponse)(nil), "v1.GetEquipmentParentsResponse")
	proto.RegisterType((*GetEquipmentRequest)(nil), "v1.GetEquipmentRequest")
	proto.RegisterType((*GetEquipmentResponse)(nil), "v1.GetEquipmentResponse")
	proto.RegisterType((*ListEquipmentsRequest)(nil), "v1.ListEquipmentsRequest")
	proto.RegisterType((*EquipFilter)(nil), "v1.EquipFilter")
	proto.RegisterType((*ListEquipmentsResponse)(nil), "v1.ListEquipmentsResponse")
	proto.RegisterType((*UpdateEquipmentTypeRequest)(nil), "v1.UpdateEquipmentTypeRequest")
	proto.RegisterType((*EquipmentMetadataRequest)(nil), "v1.EquipmentMetadataRequest")
	proto.RegisterType((*ListEquipmentMetadataRequest)(nil), "v1.ListEquipmentMetadataRequest")
	proto.RegisterType((*ListEquipmentMetadataResponse)(nil), "v1.ListEquipmentMetadataResponse")
	proto.RegisterType((*EquipmentMetadata)(nil), "v1.EquipmentMetadata")
	proto.RegisterType((*EquipmentTypesRequest)(nil), "v1.EquipmentTypesRequest")
	proto.RegisterType((*EquipmentTypesResponse)(nil), "v1.EquipmentTypesResponse")
	proto.RegisterType((*EquipmentType)(nil), "v1.EquipmentType")
	proto.RegisterType((*Attribute)(nil), "v1.Attribute")
	proto.RegisterType((*StringFilter)(nil), "v1.StringFilter")
}

func init() { proto.RegisterFile("equipment.proto", fileDescriptor_dbcd82406809d9b8) }

var fileDescriptor_dbcd82406809d9b8 = []byte{
	// 2057 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x18, 0x3d, 0x73, 0xdb, 0xc8,
	0x95, 0x00, 0x3f, 0xf1, 0x28, 0x51, 0xf0, 0x5a, 0xb2, 0x20, 0x4a, 0xb2, 0x18, 0xd8, 0x39, 0xeb,
	0x64, 0x4b, 0x38, 0xd1, 0xb9, 0xdc, 0xc5, 0xf9, 0xb2, 0x28, 0xca, 0x36, 0xc7, 0xb2, 0x24, 0x43,
	0x52, 0x2e, 0xe7, 0x7c, 0x30, 0x2b, 0x62, 0xcd, 0x43, 0x02, 0x12, 0x30, 0x00, 0xea, 0x22, 0x6b,
	0xd4, 0x38, 0x6d, 0x66, 0x6e, 0xe6, 0x32, 0x73, 0x93, 0x32, 0x55, 0x8a, 0x14, 0x69, 0x53, 0xe4,
	0x67, 0xa4, 0x49, 0x91, 0x22, 0x93, 0x49, 0x91, 0x32, 0xb5, 0x8a, 0x4c, 0x66, 0x77, 0x01, 0x90,
	0x20, 0x21, 0x4a, 0x37, 0xe7, 0xf2, 0xd8, 0x10, 0xfb, 0xde, 0xdb, 0xf7, 0xbd, 0xef, 0xbd, 0x5d,
	0x98, 0x22, 0xaf, 0x7a, 0xa6, 0xd3, 0x21, 0x5d, 0x7f, 0xcd, 0x71, 0x6d, 0xdf, 0x46, 0xe2, 0xf1,
	0x7a, 0x79, 0xa1, 0x6d, 0xdb, 0x6d, 0x8b, 0x68, 0xd8, 0x31, 0x35, 0xdc, 0xed, 0xda, 0x3e, 0xf6,
	0x4d, 0xbb, 0xeb, 0x71, 0x8a, 0x08, 0xcb, 0x56, 0x47, 0xbd, 0x97, 0x9a, 0xe7, 0xbb, 0xbd, 0x56,
	0xb0, 0xbf, 0x7c, 0x8f, 0xfd, 0xb5, 0x56, 0xdb, 0xa4, 0xbb, 0xea, 0x7d, 0x8a, 0xdb, 0x6d, 0xe2,
	0x6a, 0xb6, 0xc3, 0xf6, 0x27, 0xf0, 0x9a, 0x3d, 0xc6, 0x96, 0x69, 0x60, 0x9f, 0x68, 0xe1, 0x07,
	0x47, 0xa8, 0x5f, 0x08, 0x30, 0x73, 0xe8, 0x78, 0xc4, 0xf5, 0x9f, 0x11, 0x1f, 0x1b, 0xd8, 0xc7,
	0x3a, 0x79, 0xd5, 0x23, 0x9e, 0x8f, 0x6e, 0xc1, 0x64, 0x27, 0x00, 0x35, 0xfd, 0x13, 0x87, 0x28,
	0x42, 0x45, 0x58, 0x96, 0xf4, 0x89, 0x10, 0x78, 0x70, 0xe2, 0x10, 0x74, 0x07, 0xa6, 0x22, 0x22,
	0xcf, 0xee, 0xb9, 0x2d, 0xa2, 0x88, 0x8c, 0xac, 0x14, 0x82, 0xf7, 0x19, 0x14, 0x69, 0x70, 0x3d,
	0x22, 0xc4, 0xbe, 0xef, 0x9a, 0x47, 0x3d, 0x9f, 0x78, 0x4a, 0xba, 0x92, 0x5e, 0x96, 0x74, 0x14,
	0xa2, 0x36, 0x22, 0x8c, 0x5a, 0x85, 0x1b, 0xc3, 0x7a, 0x79, 0x8e, 0xdd, 0xf5, 0x08, 0x52, 0x20,
	0xef, 0xf5, 0x5a, 0x2d, 0xe2, 0x79, 0x4c, 0xa5, 0x82, 0x1e, 0x2e, 0xd5, 0x93, 0x70, 0xcf, 0x56,
	0xe8, 0xec, 0xd0, 0x98, 0x69, 0xc8, 0x7a, 0x2d, 0x3b, 0x32, 0x82, 0x2f, 0xd0, 0x2c, 0xe4, 0xc9,
	0x2b, 0x6e, 0x1c, 0xd7, 0x3a, 0x47, 0x5e, 0x31, 0xb3, 0xde, 0x63, 0x08, 0x2a, 0x55, 0x49, 0x57,
	0x84, 0xe5, 0x62, 0x75, 0x76, 0x8d, 0x07, 0x63, 0x2d, 0x0c, 0xc6, 0xda, 0x3e, 0x0b, 0x06, 0xdd,
	0x51, 0xc7, 0x3e, 0x56, 0xef, 0xc3, 0xec, 0x88, 0xe8, 0x4b, 0xf5, 0xfd, 0xa7, 0x08, 0x2b, 0xdb,
	0xa6, 0xd7, 0xdf, 0xe3, 0x3d, 0xb2, 0xdd, 0x3d, 0xd7, 0x36, 0x7a, 0x2d, 0x7f, 0xa3, 0xdd, 0x76,
	0x49, 0x9b, 0x05, 0x31, 0x34, 0x02, 0x41, 0xa6, 0x8b, 0x3b, 0xa1, 0x0d, 0xec, 0x1b, 0x2d, 0x00,
	0x04, 0x26, 0x34, 0x4d, 0x23, 0xb0, 0xa2, 0xc0, 0xad, 0x68, 0x18, 0xe8, 0x31, 0x14, 0x1c, 0xdc,
	0x26, 0xcd, 0x6e, 0xaf, 0xc3, 0x0c, 0xc9, 0xd6, 0xee, 0x7d, 0xbe, 0xb1, 0x54, 0x2d, 0xee, 0xe1,
	0x36, 0xa9, 0x74, 0x7b, 0x9d, 0x23, 0xe2, 0x7e, 0x9c, 0xa2, 0xbf, 0x87, 0x9f, 0x3d, 0x34, 0xd9,
	0x47, 0xea, 0xbf, 0x3f, 0x3c, 0xaf, 0xe5, 0xcb, 0x59, 0xf9, 0x3f, 0xf9, 0x65, 0x41, 0xcf, 0xd3,
	0xdd, 0x3b, 0xbd, 0x0e, 0x7a, 0x0a, 0x12, 0x63, 0xe4, 0x99, 0xaf, 0x89, 0x92, 0x61, 0x9c, 0xd6,
	0x3e, 0xdf, 0x50, 0xab, 0xa5, 0x86, 0x4f, 0x3a, 0x5e, 0xc5, 0x21, 0x6e, 0x85, 0xe2, 0x39, 0xb3,
	0xd4, 0xc7, 0x21, 0xb3, 0xdb, 0x0f, 0xcf, 0x6b, 0xb9, 0x72, 0x46, 0x36, 0x96, 0x41, 0x67, 0x9a,
	0xec, 0x9b, 0xaf, 0x99, 0xdb, 0x3d, 0xdb, 0xf5, 0x9b, 0x47, 0x27, 0x4a, 0x96, 0xbb, 0x9d, 0x2e,
	0x6b, 0x27, 0xe8, 0x1e, 0x00, 0x43, 0xd8, 0xae, 0x41, 0x5c, 0x25, 0x57, 0x11, 0x96, 0x4b, 0xd5,
	0xc9, 0xb5, 0xe3, 0xf5, 0xb5, 0x7d, 0xdb, 0xf5, 0x77, 0x29, 0x50, 0x97, 0xbc, 0xf0, 0x93, 0x26,
	0xa8, 0x47, 0xb0, 0xdb, 0xfa, 0xa4, 0xe9, 0x60, 0x17, 0x77, 0x3c, 0x25, 0xcf, 0x13, 0x94, 0x03,
	0xf7, 0x18, 0x4c, 0xfd, 0x87, 0x08, 0x4b, 0x17, 0xb9, 0x38, 0xf4, 0xeb, 0x1c, 0x14, 0xbc, 0x4f,
	0x4d, 0xa3, 0xe9, 0xe3, 0x76, 0xe0, 0xdb, 0x3c, 0x5d, 0x1f, 0xe0, 0xf6, 0xd7, 0xee, 0xbd, 0xc4,
	0xbd, 0xff, 0x13, 0x61, 0x21, 0xe6, 0xde, 0xcd, 0x4f, 0x4c, 0xcb, 0x70, 0x49, 0x94, 0xb3, 0xb3,
	0x90, 0x0f, 0xbd, 0xc7, 0x5d, 0x9b, 0xf3, 0xb9, 0xef, 0xe6, 0xa0, 0xc0, 0x4a, 0x62, 0xdf, 0xaf,
	0x79, 0xb6, 0x6e, 0x18, 0x68, 0x19, 0xe4, 0x56, 0xc0, 0x26, 0x72, 0x7d, 0x9a, 0x57, 0x95, 0x10,
	0x9e, 0x10, 0x80, 0xcc, 0x5b, 0x0b, 0x40, 0xf6, 0xed, 0x05, 0x20, 0x37, 0x26, 0x00, 0xf9, 0x2f,
	0x1b, 0x80, 0x42, 0x42, 0x00, 0x9e, 0xc3, 0x7c, 0xcc, 0xff, 0x7b, 0xd8, 0xa5, 0x49, 0xfe, 0x15,
	0xdc, 0xaf, 0x7e, 0x1f, 0xe6, 0x1f, 0x93, 0x04, 0x8e, 0x41, 0x39, 0xbb, 0x49, 0x8f, 0x44, 0x78,
	0x98, 0x02, 0xae, 0x03, 0x10, 0xb5, 0x01, 0xd7, 0x07, 0xb7, 0x7f, 0x15, 0x4d, 0xbe, 0x05, 0xd3,
	0x71, 0x56, 0x81, 0x0a, 0x0b, 0x20, 0x45, 0x02, 0x03, 0x6e, 0x7d, 0x80, 0xfa, 0x77, 0x11, 0x66,
	0xe2, 0x47, 0xfe, 0x52, 0x1d, 0xea, 0x03, 0x79, 0x24, 0xb2, 0xe8, 0xbf, 0x7b, 0x95, 0x3c, 0xca,
	0x94, 0xc5, 0x0b, 0x93, 0x28, 0xfd, 0xf6, 0x92, 0x28, 0x33, 0x26, 0x89, 0xb2, 0x5f, 0x36, 0x89,
	0x72, 0xa3, 0x49, 0x84, 0xee, 0x40, 0xee, 0xa5, 0x69, 0xf9, 0x41, 0x4e, 0x16, 0xab, 0x53, 0x94,
	0x1d, 0x73, 0xdf, 0x23, 0x06, 0xd6, 0x03, 0xb4, 0xfa, 0x27, 0x01, 0x8a, 0x03, 0x70, 0xf4, 0x01,
	0x94, 0xb0, 0xe3, 0x58, 0x66, 0x8b, 0xf5, 0xa9, 0xd0, 0xaf, 0xc5, 0xaa, 0xcc, 0xf4, 0xf1, 0x5d,
	0xb3, 0xdb, 0x0e, 0x38, 0x4c, 0x0e, 0xd0, 0x35, 0x0c, 0xa4, 0x01, 0x38, 0xbc, 0x08, 0x87, 0x61,
	0x4f, 0xda, 0x24, 0x05, 0x34, 0x0d, 0x03, 0xad, 0x43, 0xd1, 0xec, 0x7a, 0x3e, 0xee, 0xb6, 0xa2,
	0x72, 0x90, 0xb4, 0x03, 0x42, 0xa2, 0x86, 0xa1, 0xfe, 0x14, 0x6e, 0x0c, 0xa7, 0x41, 0x90, 0x3f,
	0x2a, 0x4c, 0xf8, 0xb6, 0x8f, 0x2d, 0x9d, 0xb4, 0x6c, 0xd7, 0xe0, 0x49, 0x9c, 0xd5, 0x63, 0xb0,
	0xa1, 0x34, 0xa7, 0x1a, 0x4e, 0xc4, 0xd2, 0xfc, 0xd7, 0x50, 0x3e, 0x74, 0xe8, 0x20, 0x15, 0xf1,
	0xa7, 0x35, 0x29, 0xcc, 0xb4, 0x12, 0x88, 0x51, 0x92, 0x89, 0xa6, 0x81, 0xe6, 0x69, 0x6a, 0xd0,
	0x73, 0x34, 0xd0, 0x46, 0x38, 0xa0, 0x61, 0xa0, 0x55, 0x80, 0xa1, 0x91, 0xa8, 0xc8, 0x23, 0x1a,
	0x8d, 0x43, 0xfa, 0x00, 0x81, 0xfa, 0x67, 0x01, 0x94, 0x48, 0xe8, 0xf0, 0xd4, 0x56, 0x02, 0xb1,
	0x51, 0x0f, 0x05, 0x37, 0xea, 0xe8, 0x79, 0x8c, 0xb7, 0xc8, 0xb2, 0xe5, 0x4e, 0x14, 0xde, 0x04,
	0x0e, 0x7d, 0xa1, 0x5e, 0xad, 0x70, 0x5e, 0xcb, 0xbe, 0x11, 0x44, 0x59, 0x88, 0xc9, 0xd7, 0x00,
	0xfa, 0x34, 0x28, 0x0f, 0xe9, 0x0d, 0xcb, 0x92, 0x53, 0x08, 0x20, 0xf7, 0x0c, 0x3b, 0x0e, 0x31,
	0x64, 0x01, 0x4d, 0x40, 0xe1, 0xb0, 0xdb, 0xe1, 0x2b, 0x51, 0xfd, 0x4c, 0x18, 0x6a, 0x12, 0xc3,
	0x4a, 0x6f, 0x42, 0x26, 0x9a, 0x30, 0x4b, 0xd5, 0x6f, 0x52, 0xf5, 0xc6, 0xd1, 0xaf, 0x51, 0x4f,
	0x0f, 0x28, 0xc7, 0x36, 0xab, 0x2b, 0x90, 0x61, 0xb3, 0xdb, 0x24, 0x48, 0x87, 0x3b, 0xcd, 0x67,
	0x1b, 0x7b, 0x7b, 0x5b, 0xf5, 0x40, 0x2d, 0xfe, 0x2d, 0x30, 0x5d, 0xb7, 0xb7, 0x65, 0x51, 0xd5,
	0x61, 0xf1, 0x02, 0x01, 0x41, 0x86, 0xac, 0x43, 0x21, 0x9c, 0x49, 0x15, 0x81, 0x05, 0x64, 0x26,
	0xd9, 0x69, 0x11, 0x99, 0xfa, 0x11, 0x5c, 0x1b, 0x41, 0x8f, 0x84, 0x23, 0x1c, 0xe1, 0xc4, 0x81,
	0x11, 0xee, 0xe6, 0x48, 0xf8, 0xa5, 0x98, 0xbf, 0x67, 0x61, 0x26, 0x96, 0x63, 0x61, 0x39, 0x53,
	0x0f, 0xe0, 0xc6, 0x30, 0x22, 0x50, 0xff, 0xc1, 0xc0, 0x7d, 0x83, 0xb5, 0x50, 0x2f, 0xb0, 0xe2,
	0x5a, 0xcc, 0x0a, 0x96, 0xb1, 0x25, 0x12, 0xe3, 0xa1, 0xfe, 0x46, 0x84, 0xc9, 0x18, 0xc5, 0x88,
	0x11, 0x77, 0x83, 0x70, 0x31, 0x23, 0x6a, 0xb3, 0xe7, 0xb5, 0x69, 0x17, 0x55, 0xe5, 0x9f, 0xff,
	0x64, 0xb5, 0xb9, 0xb1, 0xfa, 0x02, 0xaf, 0xbe, 0x7e, 0x6f, 0xf5, 0x3b, 0x3f, 0xbb, 0x7b, 0x9b,
	0x87, 0x25, 0x9e, 0xf9, 0xe9, 0xa1, 0xcc, 0x5f, 0x82, 0x62, 0x80, 0x64, 0x0c, 0x79, 0xa1, 0x03,
	0x0e, 0x62, 0xa2, 0x97, 0xa0, 0x18, 0x5d, 0x1b, 0x4c, 0x23, 0x98, 0x67, 0x20, 0x04, 0x35, 0x8c,
	0xa4, 0x0b, 0x48, 0x2e, 0xf1, 0x02, 0x12, 0x3f, 0x64, 0xf9, 0xcb, 0x0e, 0xd9, 0x1f, 0x33, 0x20,
	0x45, 0x98, 0x24, 0x0f, 0xf4, 0xc3, 0x38, 0xc6, 0x03, 0x2c, 0xbe, 0x1f, 0x82, 0xd4, 0xbf, 0x44,
	0xa5, 0xfb, 0xf5, 0xba, 0x1e, 0x5c, 0xa2, 0xbc, 0xda, 0xc4, 0x79, 0x4d, 0x7a, 0x23, 0xe4, 0x14,
	0x41, 0x11, 0x95, 0xb4, 0x5e, 0x88, 0x6e, 0x57, 0xd4, 0x3d, 0xae, 0xd9, 0xc1, 0xee, 0x49, 0xf3,
	0x57, 0x84, 0xf7, 0x81, 0x82, 0x0e, 0x01, 0xe8, 0x29, 0x39, 0xa1, 0x8d, 0xd0, 0x30, 0x3d, 0xc7,
	0xc2, 0x27, 0x84, 0x3b, 0xa7, 0xa0, 0xf7, 0x01, 0x34, 0xb1, 0x78, 0x99, 0xc7, 0x47, 0x16, 0x77,
	0x4b, 0x41, 0x1f, 0x80, 0xa0, 0xbb, 0x70, 0x2d, 0x0a, 0x0d, 0xe9, 0xfa, 0xe6, 0x4b, 0x33, 0xe8,
	0x00, 0x05, 0x5d, 0x0e, 0x43, 0x14, 0xc2, 0x69, 0x1c, 0xf9, 0x81, 0x6e, 0xfa, 0x76, 0x30, 0x89,
	0x14, 0x38, 0xe0, 0xc0, 0xa6, 0x7a, 0x78, 0x66, 0xa7, 0x67, 0x61, 0x9f, 0x18, 0x8a, 0xc4, 0xf5,
	0x88, 0x00, 0x68, 0x0e, 0xf2, 0x66, 0xd7, 0x6f, 0x1e, 0x63, 0x4b, 0x01, 0x5a, 0x69, 0x9f, 0xa4,
	0xf4, 0x9c, 0xd9, 0xf5, 0x7f, 0x84, 0x2d, 0xb4, 0x08, 0xd2, 0x4b, 0xcb, 0xc6, 0x1c, 0x59, 0xac,
	0x08, 0xcb, 0xe2, 0x93, 0x94, 0x5e, 0x60, 0x20, 0x8a, 0x5e, 0x02, 0xf0, 0x58, 0x79, 0x67, 0xf8,
	0x09, 0x2a, 0xf5, 0x49, 0x4a, 0x97, 0x38, 0x8c, 0x12, 0x54, 0x68, 0x5b, 0x60, 0xbb, 0x9b, 0xb6,
	0x65, 0x28, 0x93, 0x8c, 0xbd, 0xa0, 0x4b, 0x9c, 0xfd, 0xae, 0x65, 0xa0, 0xdb, 0x30, 0x19, 0x49,
	0x60, 0x34, 0x25, 0x26, 0x45, 0xd0, 0x8b, 0xa1, 0x14, 0x4a, 0xf5, 0x0e, 0x94, 0xfa, 0x82, 0x18,
	0xd9, 0x14, 0x13, 0x26, 0xe8, 0x13, 0x91, 0xb0, 0x5d, 0xcb, 0xa8, 0x65, 0x21, 0x7d, 0x8c, 0xad,
	0x9a, 0x04, 0x79, 0xdb, 0x32, 0x28, 0xad, 0xfa, 0x2f, 0x01, 0x26, 0x06, 0x5b, 0x10, 0x65, 0xc5,
	0xbb, 0xa5, 0xd9, 0x6d, 0xb3, 0x1e, 0x1c, 0xb4, 0x97, 0x21, 0x28, 0x6d, 0x42, 0x11, 0x84, 0x46,
	0x97, 0x97, 0x84, 0x18, 0x0c, 0x7d, 0x1b, 0x8a, 0x7c, 0x3d, 0x98, 0x3c, 0x33, 0xc3, 0x5d, 0x8f,
	0xd5, 0x43, 0x1d, 0x38, 0x25, 0x4b, 0x9c, 0xfb, 0x30, 0x33, 0xc8, 0xa7, 0xd9, 0xe9, 0x59, 0xbe,
	0xe9, 0x58, 0xf4, 0x84, 0xd1, 0xea, 0x32, 0x3d, 0x88, 0x7c, 0x16, 0xe0, 0xd4, 0xb9, 0xa0, 0x80,
	0x4a, 0x90, 0xd5, 0xb7, 0x1e, 0x6f, 0xfd, 0x58, 0x4e, 0xa1, 0x1c, 0x88, 0x5b, 0xcf, 0x65, 0x61,
	0xe5, 0x7d, 0x90, 0xa2, 0xe9, 0x82, 0x55, 0xd1, 0xfd, 0x4d, 0x39, 0x45, 0x3f, 0xb0, 0xd7, 0x92,
	0x53, 0xa8, 0x00, 0x99, 0xfa, 0xd6, 0xfe, 0xa6, 0x2c, 0xd0, 0x2f, 0x83, 0x78, 0x2d, 0x59, 0x28,
	0x8b, 0xb2, 0xb0, 0xf2, 0x21, 0x48, 0x51, 0x92, 0xa3, 0x22, 0xe4, 0x0f, 0x77, 0x9e, 0xee, 0xec,
	0x7e, 0xb4, 0xc3, 0xab, 0xf2, 0xfe, 0x81, 0xde, 0xd8, 0x79, 0xcc, 0xab, 0x72, 0x63, 0xe7, 0x40,
	0x16, 0xa9, 0xe0, 0x47, 0xdb, 0xbb, 0x1b, 0x07, 0x72, 0xba, 0xfa, 0xd7, 0x49, 0x90, 0xa3, 0x22,
	0xb4, 0x4f, 0xdc, 0x63, 0xb3, 0x45, 0x90, 0x0d, 0xa5, 0xf8, 0x93, 0x00, 0x9a, 0xa3, 0xae, 0x48,
	0x7c, 0xbe, 0x28, 0x97, 0x93, 0x50, 0xbc, 0x3c, 0xaa, 0xef, 0xbc, 0xf9, 0xdb, 0xbf, 0x7f, 0x27,
	0x56, 0xd4, 0x79, 0xf6, 0xf2, 0x72, 0xbc, 0xae, 0xf5, 0xfb, 0xba, 0x16, 0x96, 0x8d, 0x07, 0xc2,
	0x0a, 0x32, 0x61, 0x6a, 0xe8, 0x52, 0x8f, 0x06, 0xd8, 0x0e, 0x8f, 0xb8, 0xe5, 0xf9, 0x44, 0x5c,
	0x20, 0x73, 0x91, 0xc9, 0x9c, 0x55, 0xd1, 0xa8, 0x4c, 0x2a, 0xea, 0x8d, 0x30, 0x3c, 0xad, 0x44,
	0x46, 0x56, 0x2e, 0xeb, 0x87, 0xe5, 0x6f, 0x8c, 0xa1, 0x08, 0xc4, 0xdf, 0x62, 0xe2, 0x17, 0xd1,
	0x38, 0x93, 0x51, 0x2f, 0x3e, 0x6f, 0x47, 0x1a, 0x2c, 0x8c, 0x1b, 0x18, 0xca, 0xc9, 0x9d, 0x51,
	0x5d, 0x66, 0x12, 0x55, 0x54, 0x19, 0x23, 0x51, 0x3b, 0x6d, 0xd4, 0xcf, 0xd0, 0x2f, 0x61, 0xaa,
	0x6f, 0x36, 0x4f, 0x96, 0xb9, 0x91, 0x3e, 0xe5, 0xc5, 0x02, 0x9b, 0xdc, 0xf7, 0xd4, 0x0a, 0x93,
	0x59, 0x46, 0x4a, 0x82, 0x4c, 0xd6, 0x06, 0xd1, 0x2f, 0xe0, 0xfa, 0xa6, 0x4b, 0x86, 0xc7, 0x36,
	0x34, 0xda, 0x17, 0xcb, 0xa3, 0xa0, 0xd0, 0x89, 0xea, 0x85, 0xec, 0x69, 0x24, 0xbf, 0x10, 0xe0,
	0x7a, 0xc2, 0x64, 0x88, 0x6e, 0xf2, 0xec, 0xb8, 0x68, 0x64, 0x4c, 0x92, 0xb7, 0xcd, 0xe4, 0x3d,
	0x2a, 0x2f, 0x5e, 0x24, 0x4f, 0x3b, 0x35, 0x8d, 0xb3, 0x07, 0xc2, 0xca, 0x0b, 0xb5, 0x7a, 0x29,
	0x0d, 0xea, 0x40, 0x29, 0x9e, 0x61, 0xdc, 0xcb, 0x89, 0x57, 0x25, 0xee, 0xe5, 0xe4, 0xf1, 0x59,
	0xbd, 0xcd, 0xd4, 0xba, 0x89, 0x16, 0x12, 0x44, 0x9e, 0x06, 0x17, 0xac, 0x33, 0xe4, 0xc2, 0xc4,
	0x60, 0x32, 0xa1, 0x59, 0xca, 0x31, 0xe1, 0x66, 0x58, 0x56, 0x46, 0x11, 0x81, 0x20, 0x8d, 0x09,
	0x7a, 0x17, 0xdd, 0x19, 0x27, 0x48, 0x3b, 0x0d, 0xaf, 0x8f, 0x67, 0xe8, 0xb7, 0x02, 0x4c, 0x27,
	0x5d, 0x87, 0xd1, 0xd2, 0x88, 0x39, 0xf1, 0x8b, 0xf2, 0x58, 0x7b, 0x3f, 0x60, 0x6a, 0xac, 0x23,
	0xed, 0x8a, 0x6a, 0x68, 0x4e, 0x20, 0xf5, 0x0f, 0xc2, 0xd0, 0x4d, 0x34, 0x7c, 0x1d, 0x49, 0x38,
	0xd3, 0x43, 0x0f, 0x27, 0x63, 0x15, 0x6a, 0x30, 0x85, 0x36, 0xd1, 0xc6, 0x55, 0x15, 0x62, 0xcf,
	0x26, 0x9e, 0x76, 0x3a, 0xfc, 0xac, 0x72, 0x86, 0xfe, 0x22, 0xc0, 0xad, 0x2b, 0x3c, 0x41, 0xa2,
	0xb5, 0x51, 0x75, 0xc6, 0xbd, 0x55, 0x8e, 0x55, 0xbf, 0xce, 0xd4, 0xff, 0x01, 0xfa, 0x5e, 0xa8,
	0x7e, 0x70, 0xcd, 0xf3, 0x34, 0xdc, 0x67, 0xe4, 0x69, 0xa7, 0x74, 0x7a, 0x3a, 0x8b, 0xd9, 0xd6,
	0x7f, 0x8b, 0x3b, 0x43, 0xbf, 0x17, 0x40, 0xb9, 0x48, 0x21, 0x74, 0x6b, 0x9c, 0xba, 0x57, 0xd1,
	0xf1, 0xbb, 0x4c, 0xc7, 0xf7, 0xd1, 0xfd, 0x11, 0x1d, 0x4f, 0xc3, 0xb7, 0xc2, 0x0b, 0x55, 0xab,
	0x65, 0x5e, 0x88, 0xc7, 0xeb, 0x47, 0x39, 0xf6, 0x56, 0x7c, 0xff, 0xff, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xf6, 0xd1, 0x61, 0xe3, 0xfb, 0x17, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EquipmentServiceClient is the client API for EquipmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EquipmentServiceClient interface {
	UpsertMetadata(ctx context.Context, in *UpsertMetadataRequest, opts ...grpc.CallOption) (*UpsertMetadataResponse, error)
	UpsertEquipment(ctx context.Context, in *UpsertEquipmentRequest, opts ...grpc.CallOption) (*UpsertEquipmentResponse, error)
	ListEquipmentsMetadata(ctx context.Context, in *ListEquipmentMetadataRequest, opts ...grpc.CallOption) (*ListEquipmentMetadataResponse, error)
	GetEquipmentMetadata(ctx context.Context, in *EquipmentMetadataRequest, opts ...grpc.CallOption) (*EquipmentMetadata, error)
	EquipmentsTypes(ctx context.Context, in *EquipmentTypesRequest, opts ...grpc.CallOption) (*EquipmentTypesResponse, error)
	CreateEquipmentType(ctx context.Context, in *EquipmentType, opts ...grpc.CallOption) (*EquipmentType, error)
	// UpdateEquipmentType provides support for updating equipment
	// only addition of new attribyte is supported.
	// 1. Attributes added
	UpdateEquipmentType(ctx context.Context, in *UpdateEquipmentTypeRequest, opts ...grpc.CallOption) (*EquipmentType, error)
	ListEquipments(ctx context.Context, in *ListEquipmentsRequest, opts ...grpc.CallOption) (*ListEquipmentsResponse, error)
	GetEquipment(ctx context.Context, in *GetEquipmentRequest, opts ...grpc.CallOption) (*GetEquipmentResponse, error)
	ListEquipmentParents(ctx context.Context, in *ListEquipmentParentsRequest, opts ...grpc.CallOption) (*ListEquipmentsResponse, error)
	ListEquipmentChildren(ctx context.Context, in *ListEquipmentChildrenRequest, opts ...grpc.CallOption) (*ListEquipmentsResponse, error)
	ListEquipmentsForProductAggregation(ctx context.Context, in *ListEquipmentsForProductAggregationRequest, opts ...grpc.CallOption) (*ListEquipmentsResponse, error)
	ListEquipmentsForProduct(ctx context.Context, in *ListEquipmentsForProductRequest, opts ...grpc.CallOption) (*ListEquipmentsResponse, error)
}

type equipmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEquipmentServiceClient(cc grpc.ClientConnInterface) EquipmentServiceClient {
	return &equipmentServiceClient{cc}
}

func (c *equipmentServiceClient) UpsertMetadata(ctx context.Context, in *UpsertMetadataRequest, opts ...grpc.CallOption) (*UpsertMetadataResponse, error) {
	out := new(UpsertMetadataResponse)
	err := c.cc.Invoke(ctx, "/v1.EquipmentService/UpsertMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) UpsertEquipment(ctx context.Context, in *UpsertEquipmentRequest, opts ...grpc.CallOption) (*UpsertEquipmentResponse, error) {
	out := new(UpsertEquipmentResponse)
	err := c.cc.Invoke(ctx, "/v1.EquipmentService/UpsertEquipment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) ListEquipmentsMetadata(ctx context.Context, in *ListEquipmentMetadataRequest, opts ...grpc.CallOption) (*ListEquipmentMetadataResponse, error) {
	out := new(ListEquipmentMetadataResponse)
	err := c.cc.Invoke(ctx, "/v1.EquipmentService/ListEquipmentsMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) GetEquipmentMetadata(ctx context.Context, in *EquipmentMetadataRequest, opts ...grpc.CallOption) (*EquipmentMetadata, error) {
	out := new(EquipmentMetadata)
	err := c.cc.Invoke(ctx, "/v1.EquipmentService/GetEquipmentMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) EquipmentsTypes(ctx context.Context, in *EquipmentTypesRequest, opts ...grpc.CallOption) (*EquipmentTypesResponse, error) {
	out := new(EquipmentTypesResponse)
	err := c.cc.Invoke(ctx, "/v1.EquipmentService/EquipmentsTypes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) CreateEquipmentType(ctx context.Context, in *EquipmentType, opts ...grpc.CallOption) (*EquipmentType, error) {
	out := new(EquipmentType)
	err := c.cc.Invoke(ctx, "/v1.EquipmentService/CreateEquipmentType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) UpdateEquipmentType(ctx context.Context, in *UpdateEquipmentTypeRequest, opts ...grpc.CallOption) (*EquipmentType, error) {
	out := new(EquipmentType)
	err := c.cc.Invoke(ctx, "/v1.EquipmentService/UpdateEquipmentType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) ListEquipments(ctx context.Context, in *ListEquipmentsRequest, opts ...grpc.CallOption) (*ListEquipmentsResponse, error) {
	out := new(ListEquipmentsResponse)
	err := c.cc.Invoke(ctx, "/v1.EquipmentService/ListEquipments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) GetEquipment(ctx context.Context, in *GetEquipmentRequest, opts ...grpc.CallOption) (*GetEquipmentResponse, error) {
	out := new(GetEquipmentResponse)
	err := c.cc.Invoke(ctx, "/v1.EquipmentService/GetEquipment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) ListEquipmentParents(ctx context.Context, in *ListEquipmentParentsRequest, opts ...grpc.CallOption) (*ListEquipmentsResponse, error) {
	out := new(ListEquipmentsResponse)
	err := c.cc.Invoke(ctx, "/v1.EquipmentService/ListEquipmentParents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) ListEquipmentChildren(ctx context.Context, in *ListEquipmentChildrenRequest, opts ...grpc.CallOption) (*ListEquipmentsResponse, error) {
	out := new(ListEquipmentsResponse)
	err := c.cc.Invoke(ctx, "/v1.EquipmentService/ListEquipmentChildren", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) ListEquipmentsForProductAggregation(ctx context.Context, in *ListEquipmentsForProductAggregationRequest, opts ...grpc.CallOption) (*ListEquipmentsResponse, error) {
	out := new(ListEquipmentsResponse)
	err := c.cc.Invoke(ctx, "/v1.EquipmentService/ListEquipmentsForProductAggregation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *equipmentServiceClient) ListEquipmentsForProduct(ctx context.Context, in *ListEquipmentsForProductRequest, opts ...grpc.CallOption) (*ListEquipmentsResponse, error) {
	out := new(ListEquipmentsResponse)
	err := c.cc.Invoke(ctx, "/v1.EquipmentService/ListEquipmentsForProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EquipmentServiceServer is the server API for EquipmentService service.
type EquipmentServiceServer interface {
	UpsertMetadata(context.Context, *UpsertMetadataRequest) (*UpsertMetadataResponse, error)
	UpsertEquipment(context.Context, *UpsertEquipmentRequest) (*UpsertEquipmentResponse, error)
	ListEquipmentsMetadata(context.Context, *ListEquipmentMetadataRequest) (*ListEquipmentMetadataResponse, error)
	GetEquipmentMetadata(context.Context, *EquipmentMetadataRequest) (*EquipmentMetadata, error)
	EquipmentsTypes(context.Context, *EquipmentTypesRequest) (*EquipmentTypesResponse, error)
	CreateEquipmentType(context.Context, *EquipmentType) (*EquipmentType, error)
	// UpdateEquipmentType provides support for updating equipment
	// only addition of new attribyte is supported.
	// 1. Attributes added
	UpdateEquipmentType(context.Context, *UpdateEquipmentTypeRequest) (*EquipmentType, error)
	ListEquipments(context.Context, *ListEquipmentsRequest) (*ListEquipmentsResponse, error)
	GetEquipment(context.Context, *GetEquipmentRequest) (*GetEquipmentResponse, error)
	ListEquipmentParents(context.Context, *ListEquipmentParentsRequest) (*ListEquipmentsResponse, error)
	ListEquipmentChildren(context.Context, *ListEquipmentChildrenRequest) (*ListEquipmentsResponse, error)
	ListEquipmentsForProductAggregation(context.Context, *ListEquipmentsForProductAggregationRequest) (*ListEquipmentsResponse, error)
	ListEquipmentsForProduct(context.Context, *ListEquipmentsForProductRequest) (*ListEquipmentsResponse, error)
}

// UnimplementedEquipmentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEquipmentServiceServer struct {
}

func (*UnimplementedEquipmentServiceServer) UpsertMetadata(ctx context.Context, req *UpsertMetadataRequest) (*UpsertMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertMetadata not implemented")
}
func (*UnimplementedEquipmentServiceServer) UpsertEquipment(ctx context.Context, req *UpsertEquipmentRequest) (*UpsertEquipmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertEquipment not implemented")
}
func (*UnimplementedEquipmentServiceServer) ListEquipmentsMetadata(ctx context.Context, req *ListEquipmentMetadataRequest) (*ListEquipmentMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEquipmentsMetadata not implemented")
}
func (*UnimplementedEquipmentServiceServer) GetEquipmentMetadata(ctx context.Context, req *EquipmentMetadataRequest) (*EquipmentMetadata, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEquipmentMetadata not implemented")
}
func (*UnimplementedEquipmentServiceServer) EquipmentsTypes(ctx context.Context, req *EquipmentTypesRequest) (*EquipmentTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EquipmentsTypes not implemented")
}
func (*UnimplementedEquipmentServiceServer) CreateEquipmentType(ctx context.Context, req *EquipmentType) (*EquipmentType, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEquipmentType not implemented")
}
func (*UnimplementedEquipmentServiceServer) UpdateEquipmentType(ctx context.Context, req *UpdateEquipmentTypeRequest) (*EquipmentType, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEquipmentType not implemented")
}
func (*UnimplementedEquipmentServiceServer) ListEquipments(ctx context.Context, req *ListEquipmentsRequest) (*ListEquipmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEquipments not implemented")
}
func (*UnimplementedEquipmentServiceServer) GetEquipment(ctx context.Context, req *GetEquipmentRequest) (*GetEquipmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEquipment not implemented")
}
func (*UnimplementedEquipmentServiceServer) ListEquipmentParents(ctx context.Context, req *ListEquipmentParentsRequest) (*ListEquipmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEquipmentParents not implemented")
}
func (*UnimplementedEquipmentServiceServer) ListEquipmentChildren(ctx context.Context, req *ListEquipmentChildrenRequest) (*ListEquipmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEquipmentChildren not implemented")
}
func (*UnimplementedEquipmentServiceServer) ListEquipmentsForProductAggregation(ctx context.Context, req *ListEquipmentsForProductAggregationRequest) (*ListEquipmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEquipmentsForProductAggregation not implemented")
}
func (*UnimplementedEquipmentServiceServer) ListEquipmentsForProduct(ctx context.Context, req *ListEquipmentsForProductRequest) (*ListEquipmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEquipmentsForProduct not implemented")
}

func RegisterEquipmentServiceServer(s *grpc.Server, srv EquipmentServiceServer) {
	s.RegisterService(&_EquipmentService_serviceDesc, srv)
}

func _EquipmentService_UpsertMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).UpsertMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.EquipmentService/UpsertMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).UpsertMetadata(ctx, req.(*UpsertMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_UpsertEquipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertEquipmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).UpsertEquipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.EquipmentService/UpsertEquipment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).UpsertEquipment(ctx, req.(*UpsertEquipmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_ListEquipmentsMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEquipmentMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).ListEquipmentsMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.EquipmentService/ListEquipmentsMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).ListEquipmentsMetadata(ctx, req.(*ListEquipmentMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_GetEquipmentMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EquipmentMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).GetEquipmentMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.EquipmentService/GetEquipmentMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).GetEquipmentMetadata(ctx, req.(*EquipmentMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_EquipmentsTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EquipmentTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).EquipmentsTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.EquipmentService/EquipmentsTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).EquipmentsTypes(ctx, req.(*EquipmentTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_CreateEquipmentType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EquipmentType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).CreateEquipmentType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.EquipmentService/CreateEquipmentType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).CreateEquipmentType(ctx, req.(*EquipmentType))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_UpdateEquipmentType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEquipmentTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).UpdateEquipmentType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.EquipmentService/UpdateEquipmentType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).UpdateEquipmentType(ctx, req.(*UpdateEquipmentTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_ListEquipments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEquipmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).ListEquipments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.EquipmentService/ListEquipments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).ListEquipments(ctx, req.(*ListEquipmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_GetEquipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEquipmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).GetEquipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.EquipmentService/GetEquipment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).GetEquipment(ctx, req.(*GetEquipmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_ListEquipmentParents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEquipmentParentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).ListEquipmentParents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.EquipmentService/ListEquipmentParents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).ListEquipmentParents(ctx, req.(*ListEquipmentParentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_ListEquipmentChildren_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEquipmentChildrenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).ListEquipmentChildren(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.EquipmentService/ListEquipmentChildren",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).ListEquipmentChildren(ctx, req.(*ListEquipmentChildrenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_ListEquipmentsForProductAggregation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEquipmentsForProductAggregationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).ListEquipmentsForProductAggregation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.EquipmentService/ListEquipmentsForProductAggregation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).ListEquipmentsForProductAggregation(ctx, req.(*ListEquipmentsForProductAggregationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EquipmentService_ListEquipmentsForProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEquipmentsForProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EquipmentServiceServer).ListEquipmentsForProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.EquipmentService/ListEquipmentsForProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EquipmentServiceServer).ListEquipmentsForProduct(ctx, req.(*ListEquipmentsForProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EquipmentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.EquipmentService",
	HandlerType: (*EquipmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertMetadata",
			Handler:    _EquipmentService_UpsertMetadata_Handler,
		},
		{
			MethodName: "UpsertEquipment",
			Handler:    _EquipmentService_UpsertEquipment_Handler,
		},
		{
			MethodName: "ListEquipmentsMetadata",
			Handler:    _EquipmentService_ListEquipmentsMetadata_Handler,
		},
		{
			MethodName: "GetEquipmentMetadata",
			Handler:    _EquipmentService_GetEquipmentMetadata_Handler,
		},
		{
			MethodName: "EquipmentsTypes",
			Handler:    _EquipmentService_EquipmentsTypes_Handler,
		},
		{
			MethodName: "CreateEquipmentType",
			Handler:    _EquipmentService_CreateEquipmentType_Handler,
		},
		{
			MethodName: "UpdateEquipmentType",
			Handler:    _EquipmentService_UpdateEquipmentType_Handler,
		},
		{
			MethodName: "ListEquipments",
			Handler:    _EquipmentService_ListEquipments_Handler,
		},
		{
			MethodName: "GetEquipment",
			Handler:    _EquipmentService_GetEquipment_Handler,
		},
		{
			MethodName: "ListEquipmentParents",
			Handler:    _EquipmentService_ListEquipmentParents_Handler,
		},
		{
			MethodName: "ListEquipmentChildren",
			Handler:    _EquipmentService_ListEquipmentChildren_Handler,
		},
		{
			MethodName: "ListEquipmentsForProductAggregation",
			Handler:    _EquipmentService_ListEquipmentsForProductAggregation_Handler,
		},
		{
			MethodName: "ListEquipmentsForProduct",
			Handler:    _EquipmentService_ListEquipmentsForProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "equipment.proto",
}
