environment = "development"
debug = false
grpcport = 22090
httpport = 22091

[log]
customtimeformat = "2006-01-02T15:04:05.999999999Z07:00"
loglevel = -1

[instrumentation.prometheus]
enabled = false

[instrumentation.jaeger]
enabled = false
collectorEndpoint = "http://192.168.99.100:14268/api/traces"
agentEndpoint = "192.168.99.100:6831"
# username = ""
# password = ""

[database]
host = "localhost"
port = 5432
# should be user of full rights
[database.admin]
user = "optisam"
pass = ""
name = "simulation" 

# user of inser/update/delete/read access
[database.user]
user = "optisam_app_user"
pass = ""
name = "simulation" 

[database.migration]
version = ""
direction = "up"
migrationPath  = "./schema"

[grpcservers]
apikey = "12345678"
timeout = 10

[grpcservers.address]
license = "localhost:19091"
metric = "localhost:18090"


[iam]
publickeypath = "cert.pem"
apiKey = "12345678"
regopath = "rbac.rego"
