environment = "DEVELOPMENT"
debug = false
# Same directory will be consumed by upload service
uploaddir = "/opt/application/uploaded"
httpport = "8090"

[log]
customtimeformat = "2006-01-02T15:04:05.999999999Z07:00"
loglevel = -1

[instrumentation]
addr = ":8081"

[instrumentation.prometheus]
enabled = false

[instrumentation.jaeger]
enabled = false
collectorEndpoint = ""
agentEndpoint = ""
# username = ""
# password = ""


[pki]
publickeypath = "cert.pem"
