environment = "INTEGRATION"
debug = false
httpport = "8080"
maxfilesize = 13
#file size in Mbs
#file size in Mbs
NoOfPartitions = 3

[log]
customtimeformat = "2006-01-02T15:04:05.999999999Z07:00"
loglevel = 0

[instrumentation]
addr = ":8081"

[instrumentation.prometheus]
enabled = true


[instrumentation.jaeger]
enabled = true
serviceName = "import-service"
collectorEndpoint = "http://jaeger-collector.int-optisam.svc:14268/api/traces"
agentEndpoint = "jaeger-agent.int-optisam.svc:6831"
# username = ""
# password = ""

[database]
host = "svc-optisam-postgres.int-optisam.svc"
port = 5432
[database.admin]
user = "optisam"
name = "import"
# user of inser/update/delete/read access
[database.user]
user = "optisam_app_user"
name = "import"
# pass = ""
[database.Migration]
version = ""
direction = "up"
migrationPath  = "./schema"


[grpcservers]
apiKey = "12345678"
timeout = 10

[grpcservers.Address]
dps = "svc-optisam-dps-int.int-optisam.svc:8090"
simulation = "svc-optisam-simulation-int.int-optisam.svc:8090"
account = "svc-optisam-account-int.int-optisam.svc:8090"
catalog = "svc-optisam-catalog-int.int-optisam.svc:8090"
product = "svc-optisam-product-int.int-optisam.svc:8090"



[upload]
uploadDir = "/optisam_dir/optisam_data"
RawdataUploadDir = "/optisam_dir/optisam_rawdata"
DatafileAllowedRegex = ['''^products\.csv$''','''^products_equipments\.csv$''','''^applications_products\.csv$''',
               '''^products_acquiredRights\.csv$''',
               '''^applications\.csv$''','''^applications_instances\.csv$''','''^instances_equipments\.csv$''','''^instances_products\.csv$'''
                ,'''^equipment_[a-zA-Z]*\.csv$''']
MetaDatafileAllowedRegex = ['''^metadata_[a-zA-Z]*\.csv$''']


[iam]
publickeypath = "/opt/secret/ssh-privatekey"
apiKey = "12345678"
regopath = "rbac.rego"

[kafka]
bootstrapservers = "int-kafka-externel-bootstrap.int-optisam.svc:9094"
sslkeylocation = "/opt/secret-key/ssh-privatekey"
sslcertificatelocation = "/opt/secret-client/ssh-privatekey"
sslcalocation = "/opt/secret-ca/ssh-privatekey"
securityprotocol = "ssl"

