environment = "development"
debug = false
httpport = "9093"

[log]
customtimeformat = "2006-01-02T15:04:05.999999999Z07:00"
loglevel = -1

[instrumentation]
addr = ":8092"

[instrumentation.prometheus]
enabled = false


[instrumentation.jaeger]
enabled = false
serviceName = "import-service"
collectorEndpoint = "http://192.168.99.100:14268/api/traces"
agentEndpoint = "192.168.99.100:6831"
# username = ""
# password = ""

[database]
host = "localhost"
port = 5432
user = "postgres"
pass = "postgres"
name = "postgres"

[grpcservers]
apiKey = "12345678"
timeout = 10

[grpcservers.Address]
dps = "localhost:10000"
simulation = "localhost:22090"
account = "localhost:20000"

[upload]
uploadDir = "testdata"
RawdataUploadDir = "../../../dps-service/cmd/server/testdata/"
DatafileAllowedRegex = ['''^products\.csv$''','''^products_equipments\.csv$''','''^applications_products\.csv$''',
               '''^products_acquiredRights\.csv$''',
               '''^applications\.csv$''','''^applications_instances\.csv$''','''^instances_equipments\.csv$''','''^instances_products\.csv$'''
                ,'''^equipment_[a-zA-Z]*\.csv$''']
MetaDatafileAllowedRegex = ['''^metadata_[a-zA-Z]*\.csv$''']

[iam]
publickeypath = "cert.pem"
apiKey = "12345678"
regopath = "rbac.rego"
