environment = "development"
debug = false
httpport = "9093"
maxfilesize = 13
#file size in Mbs
NoOfPartitions = 1

[log]
customtimeformat = "2006-01-02T15:04:05.999999999Z07:00"
loglevel = 0

[instrumentation]
addr = ":8092"

[instrumentation.prometheus]
enabled = false


[instrumentation.jaeger]
enabled = false
serviceName = "import-service"
collectorEndpoint = "http://192.168.99.100:14268/api/traces"
agentEndpoint = "192.168.99.100:6831"
# username = ""
# password = ""

[database]
host = "localhost"
port = 5430
# should be user of full rights
[database.admin]
user = "root"
pass = "Optisam@19"
name = "import" 

# user of inser/update/delete/read access
[database.user]
user = "root"
pass = "Optisam@19"
name = "import"

[database.migration]
version = "1_intial_schema.sql"
direction = ""
migrationPath  = "./../../pkg/repository/v1/postgres/schema"
deleteMigrations = false

[grpcservers]
apiKey = "12345678"
timeout = 10

[grpcservers.Address]
dps = "localhost:10000"
simulation = "localhost:22090"
account = "localhost:20000"
catalog = "localhost:20024"
product = "localhost:12090"

[upload]
uploadDir = "testdata"
RawdataUploadDir = "../../../dps-service/cmd/server/testdata/"
DatafileAllowedRegex = ['''^products\.csv$''','''^products_equipments\.csv$''','''^applications_products\.csv$''',
               '''^products_acquiredRights\.csv$''',
               '''^applications\.csv$''','''^applications_instances\.csv$''','''^instances_equipments\.csv$''','''^instances_products\.csv$'''
                ,'''^equipment_[a-zA-Z]*\.csv$''']
MetaDatafileAllowedRegex = ['''^metadata_[a-zA-Z]*\.csv$''']

[iam]
publickeypath = "cert.pem"
apiKey = "12345678"
regopath = "rbac.rego"

[kafka]
bootstrapservers = "dev-kafka-externel-bootstrap-dev-optisam.apps.fr01.paas.tech.orange:443"
securityprotocol = "ssl"
sslkeylocation = "client.key.pem"
sslcertificatelocation = "client.crt.pem"
sslcalocation = "ca.crt.pem"
