environment = "DEVELOPMENT"
debug = false
grpcport = 8090
httpport = 8080
jwtprivatekey = "key.pem"

[log]
customtimeformat = "2006-01-02T15:04:05.999999999Z07:00"
loglevel = -1

[instrumentation]
addr = ":8081"

[instrumentation.prometheus]
enabled = false
namespace = "authservice"

[instrumentation.jaeger]
enabled = false
collectorEndpoint = ""
agentEndpoint = ""
# username = ""
# password = ""

[database]
host = "127.0.0.1"
port = 5432
user = "optisam"
pass = "optisam"
name = "optisam"

[dgraph]
host = "127.0.0.1:9080"