environment = "development"
debug = false
grpcport = 9092
httpport = 9093
jwtprivatekey = "key.pem"

[log]
customtimeformat = "2006-01-02T15:04:05.999999999Z07:00"
loglevel = -1

[instrumentation.prometheus]
enabled = false

[instrumentation.jaeger]
enabled = true
collectorEndpoint = "http://192.168.99.100:14268/api/traces"
agentEndpoint = "192.168.99.100:6831"
# username = ""
# password = ""

[database]
host = "localhost"
port = 5432
# should be user of full rights
[database.admin]
user = "postgres"
pass = ""
name = "account" 

# user of inser/update/delete/read access
[database.user]
user = "postgres"
pass = ""
name = "account" 

[database.migration]
version = "1.4_schema.sql,1.4.3_schema.sql,1.4.2_schema.sql"
direction = ""
migrationPath  = "./../../pkg/repository/v1/postgres/schema"