environment = "PRODUCTION"
debug = false
grpcport = 8090
httpport = 8080
jwtprivatekey = "/opt/secret-jwt/ssh-privatekey"
activationtimeout = 43200
forgotpasstimeout = 120

[log]
customtimeformat = "2006-01-02T15:04:05.999999999Z07:00"
loglevel = -1

[instrumentation]
addr = ":8081"

[instrumentation.prometheus]
enabled = true


[instrumentation.jaeger]
enabled = true
serviceName = "auth-service"
collectorEndpoint = "http://jaeger-collector.prod-optisam.svc:14268/api/traces"
agentEndpoint = "jaeger-agent.prod-optisam.svc:6831"
# username = ""
# password = ""

[database]
host = "svc-optisam-postgres.prod-optisam.svc"
port = 5432
[database.admin]
user = "optisam"
pass = ""
name = "account" 

# user of inser/update/delete/read access
[database.user]
user = "optisam_app_user"
pass = ""
name = "account" 
[database.Migration]
version = ""#version = "1.4_schema.sql;1.4.3_schema.sql;1.4.2_schema.sql"
direction = ""
migrationPath  = "./schema"

[dgraph]
host = "svc-optisam-dgraph.prod-optisam.svc:9080"

[redis]
redishost = ""
redispassword = ""
db = 0
username = ""
sentinelhost=""
sentinelport=""
sentinelmastername = ""

[emailtemplate]
passwordresetpath = "./templates/passwordreset.html"
activationpath = "./templates/activation.html"
redirecbaseurl = "https://optisam-auth-prod.apps.fr01.paas.tech.orange"
redirectappactivation = "https://optisam-ui-prod.apps.fr01.paas.tech.orange/user-activation?"
redirectappurlforgotpass = "https://optisam-ui-prod.apps.fr01.paas.tech.orange/reset-password?"

[grpcservers.Address]
notification = "svc-optisam-notification-prod.prod-optisam.svc:8090"

[httpservers.Address]
auth = "svc-optisam-auth-prod.prod-optisam.svc:80"

[iam]
publickeypath = "/opt/secret/ssh-privatekey"
apiKey = "12345678"
regopath = "rbac.rego"

[grpcservers]
apikey = "12345678"
timeout = 10000

[kafka]
bootstrapservers = "prod-kafka-externel-bootstrap.prod-optisam.svc:9094"
sslkeylocation = "/opt/secret-key/ssh-privatekey"
sslcertificatelocation = "/opt/secret-client/ssh-privatekey"
sslcalocation = "/opt/secret-ca/ssh-privatekey"
securityprotocol = "ssl"
