environment = "DEVELOPMENT"
debug = false
grpcport = 8090
httpport = 8080
jwtprivatekey = "/opt/secret/ssh-privatekey"

[log]
customtimeformat = "2006-01-02T15:04:05.999999999Z07:00"
loglevel = -1

[instrumentation]
addr = ":8081"

[instrumentation.prometheus]
enabled = true


[instrumentation.jaeger]
enabled = true
serviceName = "auth-service"
collectorEndpoint = "http://jaeger-collector.optisam-performance.svc:14268/api/traces"
agentEndpoint = "jaeger-agent.optisam-performance.svc:6831"
# username = ""
# password = ""

[database]
host = "svc-optisam-postgres.optisam-performance.svc"
port = 5432
[database.admin]
user = "optisam"
pass = ""
name = "account" 

# user of inser/update/delete/read access
[database.user]
user = "optisam_app_user"
pass = ""
name = "account" 
[database.Migration]
version = ""#version = "1.4_schema.sql;1.4.3_schema.sql;1.4.2_schema.sql"
direction = ""
migrationPath  = "./schema"


[dgraph]
host = "svc-optisam-dgraph.optisam-performance.svc:9080"
