environment = "development"
debug = false
grpcport = 5084
httpport = 6084
jwtprivatekey = "key.pem"

[log]
customtimeformat = "2006-01-02T15:04:05.999999999Z07:00"
loglevel = -1

[instrumentation.prometheus]
enabled = false

[instrumentation.jaeger]
enabled = true
collectorEndpoint = "http://localhost:14268/api/traces"
agentEndpoint = "localhost:6831"
# username = ""
# password = ""

[database]
host = "localhost"
port = 5432
user = "optisam"
pass = "optisam"
name = "account"