// Copyright (C) 2019 Orange
// 
// This software is distributed under the terms and conditions of the 'Apache License 2.0'
// license which can be found in the file 'License.txt' in this package distribution 
// or at 'http://www.apache.org/licenses/LICENSE-2.0'. 

// Code generated by MockGen. DO NOT EDIT.
// Source: gopkg.in/oauth2.v3 (interfaces: AccessGenerate)

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	oauth2 "gopkg.in/oauth2.v3"
	reflect "reflect"
)

// MockAccessGenerate is a mock of AccessGenerate interface
type MockAccessGenerate struct {
	ctrl     *gomock.Controller
	recorder *MockAccessGenerateMockRecorder
}

// MockAccessGenerateMockRecorder is the mock recorder for MockAccessGenerate
type MockAccessGenerateMockRecorder struct {
	mock *MockAccessGenerate
}

// NewMockAccessGenerate creates a new mock instance
func NewMockAccessGenerate(ctrl *gomock.Controller) *MockAccessGenerate {
	mock := &MockAccessGenerate{ctrl: ctrl}
	mock.recorder = &MockAccessGenerateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAccessGenerate) EXPECT() *MockAccessGenerateMockRecorder {
	return m.recorder
}

// Token mocks base method
func (m *MockAccessGenerate) Token(arg0 *oauth2.GenerateBasic, arg1 bool) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Token", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Token indicates an expected call of Token
func (mr *MockAccessGenerateMockRecorder) Token(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Token", reflect.TypeOf((*MockAccessGenerate)(nil).Token), arg0, arg1)
}
