environment = "DEVELOPMENT"
debug = false
grpcport = 8090
httpport = 8080

[log]
customtimeformat = "2006-01-02T15:04:05.999999999Z07:00"
loglevel = -1

[instrumentation]
addr = ":8081"

[instrumentation.prometheus]
enabled = true


[instrumentation.jaeger]
enabled = true
serviceName = "catalog-service"
collectorEndpoint = "http://jaeger-collector.dev-optisam.svc:14268/api/traces"
agentEndpoint = "jaeger-agent.dev-optisam.svc:6831"
# username = ""
# password = ""

[database]
host = "svc-optisam-postgres.dev-optisam.svc"
port = 5432
# should be user of full rights
[database.admin]
user = "optisam"
pass = ""
name = "product" 

# user of inser/update/delete/read access
[database.user]
user = "optisam_app_user"
pass = ""
name = "product" 
[database.Migration]
version = ""#version = "1.4_schema.sql;1.4.3_schema.sql;1.4.2_schema.sql"
direction = ""
migrationPath  = "./schema"

[redis]
redishost = ""
redispassword = ""
db = 0
username = ""
sentinelhost=""
sentinelport=""
sentinelmastername = ""

[pki]
publickeypath = "/opt/secret/ssh-privatekey"

[grpcservers]
apikey = "12345678"
timeout = 10000

[httpservers.Address]
auth = "svc-optisam-auth-pc.dev-optisam.svc:80"


[grpcservers.Address]
account = "svc-optisam-account-pc.dev-optisam.svc:8090"

[iam]
publickeypath = "/opt/secret/ssh-privatekey"
apiKey = "12345678"
regopath = "rbac.rego"

[application]
#usernameadmin = ""
#passwordadmin = ""
#usernamesuperadmin = ""
#passwordsuperadmin = ""
#usernameuser = ""
#passworduser = ""
