environment = "PERFORMANCE"
debug = false
grpcport = "8090"
httpport = "8080"

[log]
customtimeformat = "2006-01-02T15:04:05.999999999Z07:00"
loglevel = -1

[instrumentation]
addr = ":8081"

[instrumentation.prometheus]
enabled = true


[instrumentation.jaeger]
enabled = true
serviceName = "catalog-service"
collectorEndpoint = "http://jaeger-collector.optisam-performance.svc:14268/api/traces"
agentEndpoint = "jaeger-agent.optisam-performance.svc:6831"
# username = ""
# password = ""

[database]
host = "svc-optisam-postgres.optisam-performance.svc"
port = 5432
[database.admin]
user = "optisam"
name = "product"
# user of inser/update/delete/read access
[database.user]
user = "optisam_app_user"
name = "product"
# pass = ""
[database.Migration]
version = ""
direction = "up"
migrationPath  = "./schema"

[redis]
redishost = ""
redispassword = ""
db = 0
username = ""
sentinelhost=""
sentinelport=""
sentinelmastername = ""

[pki]
publickeypath = "/opt/secret/ssh-privatekey"

[grpcservers]
apikey = "12345678"
timeout = 1000

[httpservers.Address]
auth = "svc-optisam-auth-performance.optisam-performance.svc:80"


[grpcservers.Address]
account = "svc-optisam-acount-performance.optisam-performance.svc:8090"

[iam]
publickeypath = "/opt/secret/ssh-privatekey"
apiKey = "12345678"
regopath = "rbac.rego"

[application]
#usernameadmin = ""
#passwordadmin = ""
#usernamesuperadmin = ""
#passwordsuperadmin = ""
#usernameuser = ""
#passworduser = ""
