environment = "development"
debug = false
grpcport = 20024
httpport = 8086

[log]
customtimeformat = "2006-01-02T15:04:05.999999999Z07:00"
loglevel = -1

[instrumentation.prometheus]
enabled = false

[instrumentation.jaeger]
enabled = false
serviceName = "catalog-service"
collectorEndpoint = "http://192.168.99.100:14268/api/traces"
agentEndpoint = "192.168.99.100:6831"
# username = ""
# password = ""

[database]
host = "localhost"
port = 5432
user = "postgres"
pass = "orange"
name = "products"


[pki]
publickeypath = "cert.pem"

[grpcservers]
apikey = "12345678"
timeout = 10000


[grpcservers.Address]
account = "localhost:20000"


[iam]
publickeypath = "cert.pem"
apiKey = "12345678"
regopath = "rbac.rego"

[httpservers.Address]
auth = "localhost:9093"

[application]
#usernameadmin = ""
#passwordadmin = ""
#usernamesuperadmin = ""
#passwordsuperadmin = ""
#usernameuser = ""
#passworduser = ""