environment = "development"
debug = false
grpcport = "19091"
httpport = "19090"

[log]
customtimeformat = "2006-01-02T15:04:05.999999999Z07:00"
loglevel = -1

[instrumentation]
addr = ":8092"

[instrumentation.prometheus]
enabled = false

[instrumentation.jaeger]
enabled = false
collectorEndpoint = "http://192.168.99.100:14268/api/traces"
agentEndpoint = "192.168.99.100:6831"
# username = ""
# password = ""

[dgraph]
hosts = [
  "localhost:9080"
]

[app.params]
pageSize = 20
pageNum = 1
sortOrder = "asc"
sortBy = "name"

[iam]
publickeypath = "cert.pem"
apiKey = "12345678"
regopath = "rbac.rego"

[grpcservers]
apikey = "12345678"
timeout = 10

[grpcservers.Address]
product = "localhost:12090"