// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	DeleteConfig(ctx context.Context, arg DeleteConfigParams) error
	DeleteConfigData(ctx context.Context, configID int32) error
	GetConfig(ctx context.Context, arg GetConfigParams) (ConfigMaster, error)
	GetDataByMetadataID(ctx context.Context, metadataID int32) ([]GetDataByMetadataIDRow, error)
	GetMetadatabyConfigID(ctx context.Context, configID int32) ([]GetMetadatabyConfigIDRow, error)
	ListConfig(ctx context.Context, arg ListConfigParams) ([]ConfigMaster, error)
}

var _ Querier = (*Queries)(nil)
