---
kind: "Template"
apiVersion: "v1"
metadata:
  name: "deploy-template"
  annotations:
    description: "Template for deployment"
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: svc-optisam-meta-${ENV}
      annotations:
        description: Exposes and load balances the application pods
      labels:
        run: optisam-meta-${ENV}
    spec:
      ports:
        - name: api
          port: 80
          targetPort: 8080
          protocol: TCP
      selector:
        app: optisam-meta-${ENV}
  - kind: Route
    apiVersion: v1
    metadata:
      name: route-svc-optisam-meta-${ENV}
      labels:
        run: optisam-meta-${ENV}
    spec:
      host: optisam-meta-${ENV}.apps.fr01.paas.tech.orange
      to:
        kind: Service
        name: svc-optisam-meta-${ENV}
      port:
        targetPort: api
      tls:
        termination: edge
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: optisam-meta-${ENV}
      labels:
        app: optisam-meta-${ENV}
    spec:
      replicas: ${{REPLICAS}}
      selector:
        app: optisam-meta-${ENV}
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: optisam-meta-${ENV}
            internal-elasticsearch: 'true'
          name: optisam-meta-${ENV}
        spec:
          containers:
            - name: optisam-meta-${ENV}
              image: ${DOCKER_REGISTRY}/optisam/meta-service-${ENV}:${TAG}
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                requests:
                  cpu: "5m"
                  memory: "10Mi"
                limits:
                  cpu: "20m"
                  memory: "50Mi"
parameters:
  - name: TAG
    description: Tag for Docker image
    value: "latest"
    required: true
  - name: ENV
    description: Env for deployment
    required: true
  - name: REPLICAS
    description: Pod replica count
    value: "1"
    required: true
  - name: DOCKER_REGISTRY
    description: Artifactory URL to download images
    value: "optisam-it-virt-docker-unstable.repos.tech.orange"
    required: true
