debug = false
grpcport = "10000"
httpport = "10001"
fileslocation = "testdata"
archivelocation = "history"
rawdatalocation = "testdata"
maxfileworker = 5
maxapiworker = 100
waitlimitcount = 3


#crontime will be either in 2 formats 
#foramt-1 : "@every X" where X is any integer value combines with [s:sec,m:min,h:hour,d:day] eg : 5s/30m/20h/2h30m  -> "every 10m" for every 10 minutes
#format-2 : "s m h d M W" as cron standard "sec min hour day Mon Week" -> "0 0 0 1 * 0" for 1sday of every month for more details follow 
#https://pkg.go.dev/github.com/robfig/cron
[cron]
time = "@every 1000s"

[httpservers.Address]
auth = "localhost:9093"

[workerqueue]
Qsize = 10000
retries = 0
basedelay = 2000
ismultiqueue = true


[grpcservers]
apikey = "12345678"
timeout = 10000


[grpcservers.Address]
product = "localhost:12090"
application = "localhost:11090"
#acqright = "localhost:13090"
equipment = "localhost:14090"
account = "localhost:20000"

[log]
customtimeformat = "2006-01-02T15:04:05.999999999Z07:00"
loglevel = -1


[instrumentation]
addr = ":8081"

[instrumentation.prometheus]
enabled = false


[instrumentation.jaeger]
enabled = false
serviceName = "dps-service"
collectorEndpoint = "http://jaeger-collector.dev-optisam.svc:14268/api/traces"
agentEndpoint = "jaeger-agent.int-optisam.svc:6831"
# username = ""
# password = ""

[postgres]
host = "127.0.0.1"
port = 5432
user = "optisam"
pass = "optisam"
name = "optisam"

[app.params]
pageSize = 20
pageNum = 1
sortOrder = "asc"
sortBy = "name"

[iam]
publickeypath = "cert.pem"
apiKey = "12345678"
regopath = "rbac.rego"

