debug = false
grpcport = "5085"
httpport = "6085"
fileslocation = "optisam_data"
archivelocation = "optisam_archived"
maxfileworker = 1
maxapiworker = 10
batchsize = 40

[workerqueue]
Qsize = 1000
retries = 1
basedelay = 1000


[grpcservers]
apikey = "12345678"
timeout = 10


[grpcservers.Address]
product = "localhost:5091"
application = "localhost:5083"
acqright = "localhost:5082"
equipment = "localhost:5086"

[log]
customtimeformat = "2006-01-02T15:04:05.999999999Z07:00"
loglevel = -1


[instrumentation]
addr = ":8081"

[instrumentation.prometheus]
enabled = false
namespace = "dpsservice"

[instrumentation.jaeger]
enabled = false
serviceName = "dps-service"
collectorEndpoint = "http://localhost:14268/api/traces"
agentEndpoint = "localhost:6831"
# username = ""
# password = ""

[postgres]
host = "localhost"
port = 5432
user = "optisam"
pass = "optisam"
name = "dps"

[app.params]
pageSize = 20
pageNum = 1
sortOrder = "asc"
sortBy = "name"

[iam]
publickeypath = "cert.pem"
apiKey = "12345678"
regopath = "rbac.rego"
