include:
  # Gitleaks template
  - project: "to-be-continuous/gitleaks"
    ref: "1.2.1"
    file: "templates/gitlab-ci-gitleaks.yml"
  #- project: "to-be-continuous/sonar"
  #  ref: "1.3.2"
  #  file: "templates/gitlab-ci-sonar.yml"
  - project: 'security-dashboard/security-dashboard-template'
    ref: '0.1.21'
    file: '/templates/gitlab-ci-security-dashboard-template.yml'

.auth-template:
  before_script:
    - ls -alsh
    - chmod 777 shared-vars.sh
    - . ./shared-vars.sh
    - cd auth-service
   

.auth-lint:
  extends: .auth-template
  image: ${DOCKER_PROXY_HOST}/golangci/golangci-lint:latest-alpine
  artifacts:
    when: always
    paths:
      - ${CI_PROJECT_DIR}/auth-service/code-quality-report.json 
    reports:
      # codequality: ${CI_PROJECT_DIR}/auth-service/code-quality-report.json
      junit: ${CI_PROJECT_DIR}/auth-service/build/tests/lint-results.xml
    expire_in: 2d
  script:
    - export GO111MODULE="on"
    - export GOPROXY="${GOPROXY}"
    - golangci-lint run | tee code-quality-report.json  
    - ls -alSh
  allow_failure: true

.auth-test:
  extends: .auth-template
  services:
    - name: ${DOCKER_PROXY_HOST}/postgres:latest
      alias: postgres
  variables:
      POSTGRES_DB: optisam
      POSTGRES_USER: optisam
      POSTGRES_PASSWORD: "optisam"
  image: ${DOCKER_PROXY_HOST}/golang:${GO_VERSION}
  artifacts:
    when: always
    paths:
      - ${CI_PROJECT_DIR}/auth-service/build/tests/test-results.xml
      - ${CI_PROJECT_DIR}/auth-service/build/tests/cover.out
      - ${CI_PROJECT_DIR}/auth-service/build/tests/cover.html
    reports:
      junit: ${CI_PROJECT_DIR}/auth-service/build/tests/test-results.xml
    expire_in: 3d
  script:
    - export GOPATH="${CI_PROJECT_DIR}/auth_service"
    - export GOGC=off
    - export GO111MODULE="on"
    - export GOPROXY="${GOPROXY}"
    - mkdir -p build/tests
    - go get gotest.tools/gotestsum@v1.7.0
    - ../auth_service/bin/gotestsum --junitfile build/tests/test-results.xml -- -coverprofile=build/tests/cover.out ./...
    - go tool cover -html=build/tests/cover.out -o build/tests/cover.html
    - ls -alSh build/tests/

.auth-sonar:
  extends: .auth-template
  image: 
    name: ${DOCKER_PROXY_HOST}/sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  script:
    - chmod 777 shared-vars.sh
    - . ./shared-vars.sh
    - cd auth-service
    - sonar-scanner -Dsonar.projectName=auth-service -Dsonar.projectKey=auth-service -Dsonar.login=${SONAR_TOKEN} ${SONAR_ARGS} -X
  allow_failure: true    

.auth-build:
  extends: .auth-template
  image: ${DOCKER_PROXY_HOST}/golang:${GO_VERSION}-alpine
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/auth_service/bin/
    expire_in: 3d
  script:
    - export GOPATH="${CI_PROJECT_DIR}/auth_service"
    - export GOGC=off
    - export GO111MODULE="on"
    - export GOPROXY="${GOPROXY}"
    - export CI_BUILD_DATE=$(date +%FT%T%z)
    - (cd cmd/server; go install -v -ldflags="-X optisam-backend/auth-service/pkg/cmd.version=${CI_COMMIT_SHA} -X optisam-backend/auth-service/pkg/cmd.commitHash=${CI_COMMIT_SHA} -X optisam-backend/auth-service/pkg/cmd.buildDate=${CI_BUILD_DATE}" .)
    - ls -alSh ../auth_service/bin

.auth-package:
  extends: .auth-template
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - cd ..
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$DOCKER_REGISTRY\":{\"username\":\"$DOCKER_LOGIN\",\"password\":\"$DOCKER_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/auth-service/Dockerfile --destination ${DOCKER_REGISTRY}/optisam/auth-service:$TAG  


.auth-deploy_noprod:
  extends: .auth-template
  image: ${DOCKER_PROXY_HOST}/openshift/origin-cli:v3.11
  script:
    - echo "Creating Openshift Resources"
    - oc login ${OCP_URL}  --token=${OCP_TOKEN}   --insecure-skip-tls-verify
    - oc project ${OCP_PROJECT}
    - oc create configmap config-auth-$ENV --from-file=cmd/server/config-$ENV.toml -o yaml --dry-run | oc apply -f -
    - oc delete deploymentconfig optisam-auth
    - oc process -f auth-service.yml -p DB_PASSWORD=$DB_PASSWORD -p TAG=$TAG -p ENV=$ENV -p REPLICAS=$REPLICAS -p DOCKER_REGISTRY=$DOCKER_REGISTRY| oc apply -f -
    - oc rollout status dc/optisam-auth
    - |
      end=$((SECONDS+300))
      while [ "$(oc get pods -l=app='optisam-auth' -o jsonpath='{.items[*].status.containerStatuses[0].ready}')" != "true" ] && [ $SECONDS -lt $end ]; do
        sleep 8
        echo "Waiting for pod to be ready."
      done

.auth-deploy_prod:
  extends: .auth-template
  image: ${DOCKER_PROXY_HOST}/openshift/origin-cli:v3.11
  environment:
    name: prod
    url: https://optisam-auth-prod.apps.fr01.paas.tech.orange
  script:
    - echo "Creating Openshift Resources"
    - oc login ${OCP_URL_PROD}  --token=${OCP_TOKEN_PROD}   --insecure-skip-tls-verify
    - oc project ${OCP_PROJECT_PROD}
    - oc create configmap config-auth-prod --from-file=cmd/server/config-prod.toml -o yaml --dry-run | oc apply -f -
    - oc process -f auth-service.yml -p DB_PASSWORD=$DB_PASSWORD_PROD -p TAG=$TAG -p ENV=prod -p REPLICAS=2 -p DOCKER_REGISTRY=$DOCKER_REGISTRY| oc apply -f -
    - oc rollout status dc/optisam-auth


.auth-integration_test:
  extends: .auth-template
  image: dockerfactory-unstable-iva.si.francetelecom.fr/optisam/karate:latest
  artifacts:
    when: always
    paths:
      - ${CI_PROJECT_DIR}/auth-service/surefire-reports
      - ${CI_PROJECT_DIR}/auth-service/cucumber-html-reports
    reports:
      junit: ${CI_PROJECT_DIR}/auth-service/surefire-reports/auth.xml
    expire_in: 3d
  script:
    - java -Dkarate.config.dir=${CI_PROJECT_DIR} -jar /opt/karate/karate.jar -e=${ENV} -t ~@ignore -o ${CI_PROJECT_DIR}/auth-service/ .
    - ls -alSh
  allow_failure: true
