kind: "Template"
apiVersion: "v1"
metadata:
  name: "deploy-template"
  annotations:
    description: "Template for deployment"
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: svc-optisam-auth
      annotations:
        description: Exposes and load balances the application pods
      labels:
        run: optisam-auth
    spec:
      ports:
        - name: api
          port: 80
          targetPort: 8080
          protocol: TCP
      selector:
        app: optisam-auth
  - kind: Route
    apiVersion: v1
    metadata:
      name: route-svc-optisam-auth
      labels:
        run: optisam-auth
    spec:
      host: optisam-auth-${ENV}.apps.fr01.paas.tech.orange
      to:
        kind: Service
        name: svc-optisam-auth
      tls:
        termination: edge
  - kind: Service
    apiVersion: v1
    metadata:
      name: svc-optisam-auth-instrumentation
      annotations:
        description: Exposes and load balances the application pods
      labels:
        run: optisam-auth-instrumentation
    spec:
      ports:
        - name: api
          port: 80
          targetPort: 8081
          protocol: TCP
      selector:
        app: optisam-auth
  - kind: Route
    apiVersion: v1
    metadata:
      name: route-svc-optisam-auth-instrumentation
      labels:
        run: optisam-auth
    spec:
      host: optisam-auth-inst-${ENV}.apps.fr01.paas.tech.orange
      to:
        kind: Service
        name: svc-optisam-auth-instrumentation
      tls:
        termination: edge        
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: optisam-auth
      labels:
        app: optisam-auth
    spec:
      replicas: ${{REPLICAS}}
      selector:
        app: optisam-auth
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: optisam-auth
            internal-elasticsearch: 'true'  
          name: optisam-auth
        spec:
          containers:
            - name: optisam-auth
              image: ${DOCKER_REGISTRY}/optisam/auth-service:${TAG}
              imagePullPolicy: Always
              env:
                - name: "ENV"
                  value: ${ENV}
                - name: "DB_PASSWORD"  
                  value: ${DB_PASSWORD}
              ports:
                - containerPort: 8080
                  protocol: TCP
                - containerPort: 8081
                  protocol: TCP
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /healthz
                  port: 8081
                  scheme: HTTP
                initialDelaySeconds: 15
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 2
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /healthz
                  port: 8081
                  scheme: HTTP
                initialDelaySeconds: 15
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 2                                    
              resources:
                requests:
                  cpu: "80m"
                  memory: "128Mi"
                limits:
                  cpu: "100m"
                  memory: "150Mi"
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/config/
                - name: secret-volume
                  mountPath: /opt/secret
                  readOnly: true
          volumes:
            - name: config-volume
              configMap:
                name: config-auth-${ENV}
            - name: secret-volume
              secret:
                secretName: secret-apiprivatekey-${ENV}
parameters:
  - name: DB_PASSWORD
    description: Postgres Database Password
    required: true
  - name: TAG
    description: Tag for Docker image
    value: "latest"
    required: true
  - name: ENV
    description: Env for deployment
    required: true
  - name: REPLICAS
    description: Pod replica count
    value: "1"
    required: true
  - name: DOCKER_REGISTRY
    description: Artifactory URL to download images
    value: "dockerfactory-unstable-iva.si.francetelecom.fr"
    required: true
