environment = "development"
debug = false
grpcport = "5082"
httpport = "6082"

[log]
customtimeformat = "2006-01-02T15:04:05.999999999Z07:00"
loglevel = -1

[instrumentation]
addr = ":8092"

[instrumentation.prometheus]
enabled = false
namespace = "acqrightsservice"

[instrumentation.jaeger]
enabled = false
serviceName = "acqrights-service"
collectorEndpoint = "http://localhost/api/traces"
agentEndpoint = "localhost:6831"
# username = ""
# password = ""

[dgraph]
hosts = [
    "dgraph:9080"
]

[database]
host = "postgres"
port = 5432
user = "optisam"
pass = "optisam"
name = "acqrights"

[grpcservers]
apikey = "12345678"
timeout = 10

[grpcservers.Address]
product = "optisam-product-service:5091"

[app.params]
pageSize = 20
pageNum = 1
sortOrder = "asc"
sortBy = "name"

[iam]
publickeypath = "cert.pem"
apiKey = "12345678"
regopath = "rbac.rego"
