environment = "development"
debug = false
grpcport = "14090"
httpport = "14091"
delBatchSize = 20000

[log]
customtimeformat = "2006-01-02T15:04:05.999999999Z07:00"
loglevel = -1

[instrumentation]
addr = ":8092"

[instrumentation.prometheus]
enabled = false

[instrumentation.jaeger]
enabled = false
collectorEndpoint = "http://192.168.99.100:14268/api/traces"
agentEndpoint = "192.168.99.100:6831"
# username = ""
# password = ""

[dgraph]
hosts = [
    #"10.171.44.163:9082" 
	"127.0.0.1:9080"
]

[grpcservers]
apikey = "12345678"
timeout = 1000

[grpcservers.Address]
account = "localhost:20000"
metric = "localhost:18090"
product = "localhost:12090"

[app.params]
pageSize = 20
pageNum = 1
sortOrder = "asc"
sortBy = "name"

[iam]
publickeypath = "cert.pem"
apiKey = "12345678"
regopath = "rbac.rego"

