environment = "PERFORMANCE"
debug = false
grpcport = "8090"
httpport = "8080"

[log]
customtimeformat = "2006-01-02T15:04:05.999999999Z07:00"
loglevel = -1

[instrumentation]
addr = ":8081"

[instrumentation.prometheus]
enabled = true


[instrumentation.jaeger]
enabled = true
serviceName = "metric-service"
collectorEndpoint = "http://jaeger-collector.optisam-performance.svc:14268/api/traces"
agentEndpoint = "jaeger-agent.optisam-performance.svc:6831"
# username = ""
# password = ""

[dgraph]
hosts = [
    "svc-optisam-dgraph.optisam-performance.svc:9080"
]

[grpcservers]
apikey = "12345678"
timeout = 1000

[grpcservers.Address]
account = "svc-optisam-account.optisam-performance.svc:8090"

[app.params]
pageSize = 20
pageNum = 1
sortOrder = "asc"
sortBy = "name"

[iam]
publickeypath = "/opt/secret/ssh-privatekey"
apiKey = "12345678"
regopath = "rbac.rego"
