environment = "development"
debug = false
grpcport = 19095
httpport = 19096
#maxapiworker = 10

[log]
customtimeformat = "2006-01-02T15:04:05.999999999Z07:00"
loglevel = -1

[instrumentation.prometheus]
enabled = false

[instrumentation.jaeger]
enabled = false
serviceName = "report-service"
collectorEndpoint = "http://192.168.99.100:14268/api/traces"
agentEndpoint = "192.168.99.100:6831"
# username = ""
# password = ""

[database]
host = "localhost"
port = 5432
# should be user of full rights
[database.admin]
user = "postgres"
pass = "orange"
name = "report" 

# user of inser/update/delete/read access
[database.user]
user = "postgres"
pass = "orange"
name = "report" 

[database.migration]
version = "1.4_schema.sql,1.4.3_schema.sql,1.4.2_schema.sql"
direction = "up"
migrationPath  = "./../../pkg/repository/v1/postgres/schema"
deleteMigrations = true

[grpcservers]
apikey = "12345678"
timeout = 10

[grpcservers.Address]
license = "localhost:8090"
product = "localhost:12090"

[dgraph]
hosts = [
#    "10.171.44.163:9081"
"localhost:9080"
]

[iam]
publickeypath = "cert.pem"
apiKey = "12345678"
regopath = "rbac.rego"
