environment = "PRODUCTION"
debug = false
grpcport = 8090
httpport = 8080

[log]
customtimeformat = "2006-01-02T15:04:05.999999999Z07:00"
loglevel = -1

[instrumentation]
addr = ":8081"

[instrumentation.prometheus]
enabled = true


[instrumentation.jaeger]
enabled = true
serviceName = "report-service"
collectorEndpoint = "http://jaeger-collector.prod-optisam.svc:14268/api/traces"
agentEndpoint = "jaeger-agent.prod-optisam.svc:6831"
# username = ""
# password = ""

[grpcservers]
apikey = "12345678"
timeout = 10

[grpcservers.Address]
license = "svc-optisam-license-prod.prod-optisam.svc:8090"
product = "svc-optisam-product-prod.prod-optisam.svc:8090"

[database]
host = "svc-optisam-postgres.prod-optisam.svc"
port = 5432
# should be user of full rights
[database.admin]
user = "optisam"
pass = ""
name = "report" 

# user of inser/update/delete/read access
[database.user]
user = "optisam_app_user"
pass = ""
name = "report" 

[database.migration]
version = ""
direction = "up"
migrationPath  = "./schema"

[dgraph]
hosts = [
    "svc-optisam-dgraph.prod-optisam.svc:9080"
]

[iam]
publickeypath = "/opt/secret/ssh-privatekey"
apiKey = "12345678"
regopath = "rbac.rego"
