kind: "Template"
apiVersion: "v1"
metadata:
  name: "deploy-template"
  annotations:
    description: "Template for deployment"
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: svc-optisam-license-${ENV}
      annotations:
        description: Exposes and load balances the application pods
      labels:
        run: optisam-license-${ENV}
    spec:
      ports:
        - name: api
          port: 80
          targetPort: 8080
          protocol: TCP
        - name: instapi
          port: 81
          targetPort: 8081
          protocol: TCP          
        - name: grpc
          port: 8090
          targetPort: 8090
          protocol: TCP
      selector:
        app: optisam-license-${ENV}
  - kind: Route
    apiVersion: v1
    metadata:
      name: route-svc-optisam-license-${ENV}
      labels:
        run: optisam-license-${ENV}
    spec:
      host: optisam-license-${ENV}.apps.fr01.paas.tech.orange
      to:
        kind: Service
        name: svc-optisam-license-${ENV}
      port:
        targetPort: api
      tls:
        termination: edge
  - kind: Route
    apiVersion: v1
    metadata:
      name: route-svc-optisam-license-instrumentation-${ENV}
      labels:
        run: optisam-license-${ENV}
    spec:
      host: optisam-license-inst-${ENV}.apps.fr01.paas.tech.orange
      to:
        kind: Service
        name: svc-optisam-license-${ENV}
      port:
        targetPort: instapi        
      tls:
        termination: edge
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: optisam-license-${ENV}
      labels:
        app: optisam-license-${ENV}
    spec:
      replicas: ${{REPLICAS}}
      selector:
        app: optisam-license-${ENV}
      strategy:
        type: Rolling
      template:
        metadata:
          annotations:
            prometheus.io/port: '8081'
            prometheus.io/scrape: 'true'
          labels:
            app: optisam-license-${ENV}
            internal-elasticsearch: 'true'  
          name: optisam-license-${ENV}
        spec:
          containers:
            - name: optisam-license-${ENV}
              image: ${DOCKER_REGISTRY}/optisam/license-service-${ENV}:${TAG}
              imagePullPolicy: Always
              env:
                - name: "ENV"
                  value: ${ENV}
                - name: "DB_PASSWORD"  
                  value: ${DB_PASSWORD}
              envFrom:
                - secretRef:
                       name: user-access
              ports:
                - containerPort: 8080
                  protocol: TCP
                - containerPort: 8090
                  protocol: TCP
                - containerPort: 8081
                  protocol: TCP
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /healthz
                  port: 8081
                  scheme: HTTP
                initialDelaySeconds: 15
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 2
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /healthz
                  port: 8081
                  scheme: HTTP
                initialDelaySeconds: 15
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 2
              resources:
                requests:
                  cpu: "100m"
                  memory: "128Mi"
                limits:
                  cpu: "120m"
                  memory: "150Mi"
              volumeMounts:
                - name: config-volume-${ENV}
                  mountPath: /opt/config
                - name: secret-volume
                  mountPath: /opt/secret
                  readOnly: true
          volumes:
            - name: config-volume-${ENV}
              configMap:
                name: config-license-${ENV}
            - name: secret-volume
              secret:
                secretName: secret-apipublickey-${ENV}
parameters:
  - name: DB_PASSWORD
    description: Postgres Database Password
    required: true
  - name: TAG
    description: Tag for Docker image
    value: "latest"
    required: true
  - name: ENV
    description: Env for deployment
    required: true
  - name: REPLICAS
    description: Pod replica count
    value: "1"
    required: true
  - name: DOCKER_REGISTRY
    description: Artifactory URL to download images
    value: "optisam-it-virt-docker-unstable.repos.tech.orange"
    required: true
