environment = "DEVELOPMENT"
debug = false
grpcport = 8090
httpport = 8080

[log]
customtimeformat = "2006-01-02T15:04:05.999999999Z07:00"
loglevel = -1

[instrumentation]
addr = ":8081"

[instrumentation.prometheus]
enabled = true


[instrumentation.jaeger]
enabled = true
serviceName = "account-service"
collectorEndpoint = "http://jaeger-collector.dev-optisam.svc:14268/api/traces"
agentEndpoint = "jaeger-agent.dev-optisam.svc:6831"
# username = ""
# password = ""

[database]
host = "svc-optisam-postgres.dev-optisam.svc"
port = 5432
user = "optisam"
#pass = ""
name = "account"

[pki]
publickeypath = "/opt/secret/ssh-privatekey"

[grpcservers]
apikey = "12345678"
timeout = 10000


[grpcservers.Address]
product = "svc-optisam-product.dev-optisam.svc:8090"
application = "svc-optisam-application.dev-optisam.svc:8090"
dps = "svc-optisam-dps.dev-optisam.svc:8090"
metric = "svc-optisam-metric.dev-optisam.svc:8090"
equipment = "svc-optisam-equipment.dev-optisam.svc:8090"
report = "svc-optisam-report.dev-optisam.svc:8090"

[iam]
publickeypath = "/opt/secret/ssh-privatekey"
apiKey = "12345678"
regopath = "rbac.rego"