environment = "PRODUCTION"
debug = false
grpcport = 8090
httpport = 8080

[log]
customtimeformat = "2006-01-02T15:04:05.999999999Z07:00"
loglevel = -1

[instrumentation]
addr = ":8081"

[instrumentation.prometheus]
enabled = true


[instrumentation.jaeger]
enabled = true
serviceName = "account-service"
collectorEndpoint = "http://jaeger-collector.prod-optisam.svc:14268/api/traces"
agentEndpoint = "jaeger-agent.prod-optisam.svc:6831"
# username = ""
# password = ""

[database]
host = "svc-optisam-postgres.prod-optisam.svc"
port = 5432
[database.admin]
user = "optisam"
pass = ""
name = "account" 

# user of inser/update/delete/read access
[database.user]
user = "optisam_app_user"
pass = ""
name = "account" 
[database.Migration]
version = ""#version = "1.4_schema.sql;1.4.3_schema.sql;1.4.2_schema.sql"
direction = ""
migrationPath  = "./schema"

[redis]
redishost = ""
redispassword = ""
db = 0
username = ""
sentinelhost=""
sentinelport=""
sentinelmastername = ""

[pki]
publickeypath = "/opt/secret/ssh-privatekey"

[grpcservers]
apikey = "12345678"
timeout = 10000


[grpcservers.Address]
product = "svc-optisam-product-prod.prod-optisam.svc:8090"
application = "svc-optisam-application-prod.prod-optisam.svc:8090"
dps = "svc-optisam-dps-prod.prod-optisam.svc:8090"
metric = "svc-optisam-metric-prod.prod-optisam.svc:8090"
equipment = "svc-optisam-equipment-prod.prod-optisam.svc:8090"
report = "svc-optisam-report-prod.prod-optisam.svc:8090"

[iam]
publickeypath = "/opt/secret/ssh-privatekey"
apiKey = "12345678"
regopath = "rbac.rego"
