environment = "DEVELOPMENT"
debug = false
grpcport = 9092
httpport = 9093

[log]
customtimeformat = "2006-01-02T15:04:05.999999999Z07:00"
loglevel = -1

[instrumentation]
addr = ":8081"

[instrumentation.prometheus]
enabled = false
namespace = "accountservice"

[instrumentation.jaeger]
enabled = false
collectorEndpoint = ""
agentEndpoint = ""
# username = ""
# password = ""

[database]
host = "db"
port = 5432
user = "optisam"
pass = "optisam"
name = "optisam"

[pki]
publickeypath = "cert.pem"