environment = "development"
debug = false
grpcport = 20000
httpport = 20001

[log]
customtimeformat = "2006-01-02T15:04:05.999999999Z07:00"
loglevel = 0

[instrumentation.prometheus]
enabled = false

[instrumentation.jaeger]
enabled = false
serviceName = "account-service"
collectorEndpoint = "http://192.168.99.100:14268/api/traces"
agentEndpoint = "192.168.99.100:6831"
# username = ""
# password = ""

[database]
host = "localhost"
port = 5432
# should be user of full rights
[database.admin]
user = "postgres"
pass = ""
name = "account" 

# user of inser/update/delete/read access
[database.user]
user = "postgres"
pass = ""
name = "account" 

[database.migration]
version = "1.4_schema.sql,1.4.3_schema.sql,1.4.2_schema.sql"
direction = ""
migrationPath  = "./../../pkg/repository/v1/postgres/schema"

[redis]
redishost = "localhost:6379"
redispassword = ""
db = 0
username = ""
sentinelhost=""
sentinelport=""
sentinelmastername = ""

[pki]
publickeypath = "cert.pem"

[grpcservers]
apikey = "12345678"
timeout = 10000


[grpcservers.Address]
#product = "localhost:12090"
#application = "localhost:11090"
#dps = "localhost:10000"
#metric = "localhost:18090"
#equipment = "localhost:14090"
#report = "localhost:19090"

[iam]
publickeypath = "cert.pem"
apiKey = "12345678"
regopath = "rbac.rego"
