environment = "INTEGRATION"
debug = false
grpcport = 8090
httpport = 8080
activationtimeout = 43200
forgotpasstimeout = 120

[log]
customtimeformat = "2006-01-02T15:04:05.999999999Z07:00"
loglevel = -1

[instrumentation]
addr = ":8081"

[instrumentation.prometheus]
enabled = true


[instrumentation.jaeger]
enabled = true
serviceName = "account-service"
collectorEndpoint = "http://jaeger-collector.int-optisam.svc:14268/api/traces"
agentEndpoint = "jaeger-agent.int-optisam.svc:6831"
# username = ""
# password = ""

[database]
host = "svc-optisam-postgres.int-optisam.svc"
port = 5432
[database.admin]
user = "optisam"
pass = ""
name = "account" 

# user of inser/update/delete/read access
[database.user]
user = "optisam_app_user"
pass = ""
name = "account" 
[database.Migration]
version = ""#version = "1.4_schema.sql;1.4.3_schema.sql;1.4.2_schema.sql"
direction = ""
migrationPath  = "./schema"

[redis]
redishost = ""
redispassword = ""
db = 0
username = ""
sentinelhost=""
sentinelport=""
sentinelmastername = ""

[pki]
publickeypath = "/opt/secret/ssh-privatekey"

[grpcservers]
apikey = "12345678"
timeout = 10000


[grpcservers.Address]
product = "svc-optisam-product-int.int-optisam.svc:8090"
application = "svc-optisam-application-int.int-optisam.svc:8090"
dps = "svc-optisam-dps-int.int-optisam.svc:8090"
metric = "svc-optisam-metric-int.int-optisam.svc:8090"
equipment = "svc-optisam-equipment-int.int-optisam.svc:8090"
report = "svc-optisam-report-int.int-optisam.svc:8090"
notification = "svc-optisam-notification-int.int-optisam.svc:8090"

[iam]
publickeypath = "/opt/secret/ssh-privatekey"
apiKey = "12345678"
regopath = "rbac.rego"


[emailtemplate]
passwordresetpath = "./templates/passwordreset.html"
activationpath = "./templates/activation.html"
redirecbaseurl = "https://optisam-auth-int.apps.fr01.paas.tech.orange"
redirectappactivation = "https://optisam-ui-int.apps.fr01.paas.tech.orange/user-activation?"
redirectappurlforgotpass = "https://optisam-ui-int.apps.fr01.paas.tech.orange/reset-password?"

[httpservers.Address]
auth = "svc-optisam-auth-int.int-optisam.svc:80"