environment = "development"
debug = false
grpcport = 5081
httpport = 6081

[log]
customtimeformat = "2006-01-02T15:04:05.999999999Z07:00"
loglevel = -1

[instrumentation.prometheus]
enabled = false

[instrumentation.jaeger]
enabled = false
serviceName = "account-service"
collectorEndpoint = "http://loc:14268/api/traces"
agentEndpoint = "localhost:6831"
# username = ""
# password = ""

[database]
host = "localhost"
port = 5432
user = "optisam"
pass = "optisam"
name = "account"

[pki]
publickeypath = "cert.pem"