version: "3"
networks:
  dgraph:
services:
  zero_1:
    image: dgraph/dgraph:latest
    volumes:
      - data-volume_zero_1:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    networks:
      - dgraph
    command: dgraph zero --my=zero_1:5080 --replicas 3 --idx 1
  zero_2:
    image: dgraph/dgraph:latest
    volumes:
      - data-volume_zero_2:/dgraph
    ports:
      - 5081:5081
      - 6081:6081
    networks:
      - dgraph
    command: dgraph zero -o 1 --my=zero_2:5081 --replicas 3 --peer zero_1:5080 --idx 2
  zero_3:
    image: dgraph/dgraph:latest
    volumes:
      - data-volume_zero_3:/dgraph
    ports:
      - 5082:5082
      - 6082:6082
    networks:
      - dgraph
    command: dgraph zero -o 2 --my=zero_3:5082 --replicas 3 --peer zero_1:5080 --idx 3
  alpha_1:
    image: dgraph/dgraph:latest
    hostname: "alpha_1"
    volumes:
      - data-volume_aplph_1:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    networks:
      - dgraph
    command: dgraph alpha --my=alpha_1:7080 --lru_mb=2048 --zero=zero_1:5080
  alpha_2:
    image: dgraph/dgraph:latest
    hostname: "alpha_2"
    volumes:
      - data-volume_aplph_2:/dgraph
    ports:
      - 7086:8081
      - 9081:9081
    networks:
      - dgraph
    command: dgraph alpha --my=alpha_2:7081 --lru_mb=2048 --zero=zero_1:5080 -o 1
  alpha_3:
    image: dgraph/dgraph:latest
    hostname: "alpha_3"
    volumes:
      - data-volume_aplph_3:/dgraph
    ports:
      - 8082:8082
      - 9082:9082
    networks:
      - dgraph
    command: dgraph alpha --my=alpha_3:7082 --lru_mb=2048 --zero=zero_1:5080 -o 2
  alpha_4:
    image: dgraph/dgraph:latest
    hostname: "alpha_4"
    volumes:
      - data-volume_aplph_4:/dgraph
    ports:
      - 8083:8083
      - 9083:9083
    networks:
      - dgraph
    command: dgraph alpha --my=alpha_4:7083 --lru_mb=2048 --zero=zero_1:5080 -o 3
  alpha_5:
    image: dgraph/dgraph:latest
    hostname: "alpha_5"
    volumes:
      - data-volume_aplph_5:/dgraph
    ports:
      - 8084:8084
      - 9084:9084
    networks:
      - dgraph
    command: dgraph alpha --my=alpha_5:7084 --lru_mb=2048 --zero=zero_1:5080 -o 4
  alpha_6:
    image: dgraph/dgraph:latest
    hostname: "alpha_6"
    volumes:
      - data-volume_aplph_6:/dgraph
    ports:
      - 8085:8085
      - 9085:9085
    networks:
      - dgraph
    command: dgraph alpha --my=alpha_6:7085 --lru_mb=2048 --zero=zero_1:5080 -o 5
  ratel:
    image: dgraph/dgraph:latest
    hostname: "ratel"
    ports:
      - 8000:8000
    networks:
      - dgraph
    command: dgraph-ratel
volumes:
  data-volume_zero_1:
  data-volume_zero_2:
  data-volume_zero_3:
  data-volume_aplph_1:
  data-volume_aplph_2:
  data-volume_aplph_3:
  data-volume_aplph_4:
  data-volume_aplph_5:
  data-volume_aplph_6:
