.import-template:
  before_script:
    - ls -lash
    - chmod 777 shared-vars.sh
    - . ./shared-vars.sh
    - cd import-service
   

.import-lint:
  extends: .import-template
  image: ${DOCKER_PROXY_HOST}/golangci/golangci-lint:latest-alpine
  artifacts:
    when: always
    paths:
      - ${CI_PROJECT_DIR}/license-service/code-quality-report.json 
    reports:
      codequality: ${CI_PROJECT_DIR}/license-service/code-quality-report.json
      ## junit: ${CI_PROJECT_DIR}/license-service/build/tests/lint-results.xml
    expire_in: 2d
  script:
    - export GO111MODULE="on"
    - export GOPROXY="${GOPROXY}"
    - golangci-lint run | tee code-quality-report.json  
    - ls -alSh
  allow_failure: true

.import-test:
  extends: .import-template
  services:
    - name: ${DOCKER_PROXY_HOST}/postgres:${POSTGRES_VERSION}-alpine
      alias: postgres
  variables:
      POSTGRES_DB: optisam
      POSTGRES_USER: optisam
      POSTGRES_PASSWORD: "optisam"
  image: ${DOCKER_PROXY_HOST}/golang:${GO_VERSION}
  artifacts:
    when: always
    paths:
      - ${CI_PROJECT_DIR}/import-service/build/tests/test-results.xml
      - ${CI_PROJECT_DIR}/import-service/build/tests/cover.out
      - ${CI_PROJECT_DIR}/import-service/build/tests/cover.html
    reports:
      junit: ${CI_PROJECT_DIR}/import-service/build/tests/test-results.xml
    expire_in: 3d
  script:
    - export GOPATH="${CI_PROJECT_DIR}/import_service"
    - export GOGC=off
    - export GO111MODULE="on"
    - export GOPROXY="${GOPROXY}"
    - mkdir -p build/tests
    - go get gotest.tools/gotestsum@v1.7.0
    - cd pkg/service
    - ../../../import_service/bin/gotestsum --junitfile ../../build/tests/test-results.xml -- -coverprofile=../../build/tests/cover.out ./...
    - go tool cover -html=../../build/tests/cover.out -o ../../build/tests/cover.html
    - ls -alSh ../../build/tests/

.import-sonar:
  extends: .import-template
  image: 
    name: ${DOCKER_PROXY_HOST}/sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  script:
    - chmod 777 shared-vars.sh
    - . ./shared-vars.sh
    - cd import-service
    - sonar-scanner -Dsonar.projectName=import-service -Dsonar.projectKey=import-service -Dsonar.login=${SONAR_TOKEN} ${SONAR_ARGS} -X
  allow_failure: true  

.import-build:
  extends: .import-template
  image: ${DOCKER_PROXY_HOST}/golang:${GO_VERSION}-alpine
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/import_service/bin/
    expire_in: 3d
  script:
    - export GOPATH="${CI_PROJECT_DIR}/import_service"
    - export GOGC=off
    - export GO111MODULE="on"
    - export GOPROXY="${GOPROXY}"
    - export CI_BUILD_DATE=$(date +%FT%T%z)
    - (cd cmd/server; go install -v -ldflags="-X optisam-backend/import-service/pkg/cmd.version=${CI_COMMIT_SHA} -X optisam-backend/import-service/pkg/cmd.commitHash=${CI_COMMIT_SHA} -X optisam-backend/import-service/pkg/cmd.buildDate=${CI_BUILD_DATE}" .)
    - ls -alSh ../import_service/bin

.import-package:
  extends: .import-template
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - cd ..
    - mkdir -p /kaniko/.docker
    - echo $DOCKER_AUTH_CONFIG > /kaniko/.docker/config.json
      # - echo "{\"auths\":{\"$DOCKER_REGISTRY\":{\"username\":\"$DOCKER_LOGIN\",\"password\":\"$DOCKER_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/import-service/Dockerfile --destination ${DOCKER_REGISTRY}/optisam/import-service:$TAG

.import-deploy_noprod:
  extends: .import-template
  image: ${DOCKER_PROXY_HOST}/openshift/origin-cli:v3.11
  script:
    - echo "Creating Openshift Resources"
    - oc login ${OCP_URL}  --token=${OCP_TOKEN}   --insecure-skip-tls-verify
    - oc project ${OCP_PROJECT}
    - oc create configmap config-import-$ENV --from-file=cmd/server/config-$ENV.toml -o yaml --dry-run | oc apply -f -
    - oc delete deploymentconfig optisam-import
    - oc process -f import-service.yml -p DB_PASSWORD=$DB_PASSWORD -p TAG=$TAG -p ENV=$ENV -p REPLICAS=$REPLICAS -p DOCKER_REGISTRY=$DOCKER_REGISTRY| oc apply -f -
    - oc rollout status dc/optisam-import
    - |
      end=$((SECONDS+300))
      while [ "$(oc get pods -l=app='optisam-import' -o jsonpath='{.items[*].status.containerStatuses[0].ready}')" != "true" ] && [ $SECONDS -lt $end ]; do
        sleep 8
        echo "Waiting for pod to be ready."
      done

.import-deploy_prod:
  extends: .import-template
  image: ${DOCKER_PROXY_HOST}/openshift/origin-cli:v3.11
  environment:
    name: prod
    url: https://optisam-import-prod.apps.fr01.paas.tech.orange
  script:
    - echo "Creating Openshift Resources"
    - oc login ${OCP_URL_PROD}  --token=${OCP_TOKEN_PROD}   --insecure-skip-tls-verify
    - oc project ${OCP_PROJECT_PROD}
    - oc create configmap config-import-prod --from-file=cmd/server/config-prod.toml -o yaml --dry-run | oc apply -f -
    - oc process -f import-service.yml -p DB_PASSWORD=$DB_PASSWORD_PROD -p TAG=$TAG -p ENV=prod -p REPLICAS=2 -p DOCKER_REGISTRY=$DOCKER_REGISTRY| oc apply -f -
    - oc rollout status dc/optisam-import
