kind: "Template"
apiVersion: "v1"
metadata:
  name: "deploy-template"
  annotations:
    description: "Template for deployment"
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: svc-optisam-import-new
      annotations:
        description: Exposes and load balances the application pods
      labels:
        run: optisam-import-new
    spec:
      ports:
        - name: api
          port: 80
          targetPort: 8080
          protocol: TCP
      selector:
        app: optisam-import-new
  - kind: Route
    apiVersion: v1
    metadata:
      annotations:
          haproxy.router.openshift.io/timeout: 300s
      name: route-svc-optisam-import-new
      labels:
        run: optisam-import-new
    spec:
      host: optisam-import-new-${ENV}.apps.fr01.paas.tech.orange
      to:
        kind: Service
        name: svc-optisam-import-new
      tls:
        termination: edge
  - kind: Service
    apiVersion: v1
    metadata:
      name: svc-optisam-import-instrumentation-new
      annotations:
        description: Exposes and load balances the application pods
      labels:
        run: optisam-import-instrumentation-new
    spec:
      ports:
        - name: api
          port: 80
          targetPort: 8081
          protocol: TCP
      selector:
        app: optisam-import-new
  - kind: Route
    apiVersion: v1
    metadata:
      name: route-svc-optisam-import-instrumentation-new
      labels:
        run: optisam-import-new
    spec:
      host: optisam-import-inst-new-${ENV}.apps.fr01.paas.tech.orange
      to:
        kind: Service
        name: svc-optisam-import-instrumentation-new
      tls:
        termination: edge
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: optisam-import-new
      labels:
        app: optisam-import-new
    spec:
      replicas: ${{REPLICAS}}
      selector:
        app: optisam-import-new
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: optisam-import-new
            internal-elasticsearch: 'true'  
          name: optisam-import-new
        spec:
          containers:
            - name: optisam-import-new
              image: ${DOCKER_REGISTRY}/optisam/import-service-new:${TAG}
              imagePullPolicy: Always
              env:
                - name: "ENV"
                  value: ${ENV}
                - name: "DB_PASSWORD"  
                  value: ${DB_PASSWORD}
              ports:
                - containerPort: 8080
                  protocol: TCP
                - containerPort: 8081
                  protocol: TCP
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /healthz
                  port: 8081
                  scheme: HTTP
                initialDelaySeconds: 15
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 2
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /healthz
                  port: 8081
                  scheme: HTTP
                initialDelaySeconds: 15
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 2
              resources:
                requests:
                  cpu: "80m"
                  memory: "300Mi"
                limits:
                  cpu: "100m"
                  memory: "1200Mi"
              volumeMounts:
                - name: config-volume-new
                  mountPath: /opt/config/
                - name: optisam-dir
                  mountPath: /optisam_dir
                - name: secret-volume
                  mountPath: /opt/secret
                  readOnly: true
          volumes:
            - name: config-volume-new
              configMap:
                name: config-import-new-${ENV}
            - name: optisam-dir
              persistentVolumeClaim:
                claimName: optisam-storage
            - name: secret-volume
              secret:
                secretName: secret-apipublickey-${ENV}
parameters:
  - name: DB_PASSWORD
    description: Postgres Database Password
    required: true
  - name: TAG
    description: Tag for Docker image
    value: latest
    required: true
  - name: ENV
    description: Env for deployment
    required: true
  - name: REPLICAS
    description: Pod replica count
    value: "1"
    required: true
  - name: DOCKER_REGISTRY
    description: Artifactory URL to download images
    value: "optisam-it-virt-docker-unstable.repos.tech.orange"
    required: true
