---
kind: "Template"
apiVersion: "v1"
metadata:
  name: "deploy-template"
  annotations:
    description: "Template for deployment"
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: svc-optisam-import-${ENV}
      annotations:
        description: Exposes and load balances the application pods
      labels:
        run: optisam-import-${ENV}
    spec:
      ports:
        - name: api
          port: 80
          targetPort: 8080
          protocol: TCP
      selector:
        app: optisam-import-${ENV}
  - kind: Route
    apiVersion: v1
    metadata:
      annotations:
        haproxy.router.openshift.io/timeout: 300s
      name: route-svc-optisam-import-${ENV}
      labels:
        run: optisam-import-${ENV}
    spec:
      host: optisam-import-${ENV}.apps.fr01.paas.tech.orange
      to:
        kind: Service
        name: svc-optisam-import-${ENV}
      tls:
        termination: edge
  - kind: Service
    apiVersion: v1
    metadata:
      name: svc-optisam-import-instrumentation-${ENV}
      annotations:
        description: Exposes and load balances the application pods
      labels:
        run: optisam-import-instrumentation-${ENV}
    spec:
      ports:
        - name: api
          port: 80
          targetPort: 8081
          protocol: TCP
      selector:
        app: optisam-import-${ENV}
  - kind: Route
    apiVersion: v1
    metadata:
      name: route-svc-optisam-import-instrumentation-${ENV}
      labels:
        run: optisam-import-${ENV}
    spec:
      host: optisam-import-inst-${ENV}.apps.fr01.paas.tech.orange
      to:
        kind: Service
        name: svc-optisam-import-instrumentation-${ENV}
      tls:
        termination: edge
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: optisam-import-${ENV}
      labels:
        app: optisam-import-${ENV}
    spec:
      replicas: ${{REPLICAS}}
      selector:
        app: optisam-import-${ENV}
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: optisam-import-${ENV}
            internal-elasticsearch: 'true'
          name: optisam-import-${ENV}
        spec:
          containers:
            - name: optisam-import-${ENV}
              image: ${DOCKER_REGISTRY}/optisam/import-service-${ENV}:${TAG}
              imagePullPolicy: Always
              env:
                - name: "ENV"
                  value: ${ENV}
                - name: "MIG_DIR"
                  value: ${MIG_DIR}
                - name: "MIG_VERSION"
                  value: ${MIG_VERSION}
              envFrom:
                - secretRef:
                    name: user-access
                - secretRef:
                    name: db-access
                - secretRef:
                    name: db-pass
              ports:
                - containerPort: 8080
                  protocol: TCP
                - containerPort: 8081
                  protocol: TCP
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /healthz
                  port: 8081
                  scheme: HTTP
                initialDelaySeconds: 15
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 2
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /healthz
                  port: 8081
                  scheme: HTTP
                initialDelaySeconds: 15
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 2
              resources:
                requests:
                  cpu: "1m"
                  memory: "5Mi"
                limits:
                  cpu: "1000m"
                  memory: "1200Mi"
              volumeMounts:
                - name: config-volume-${ENV}
                  mountPath: /opt/config/
                - name: optisam-dir
                  mountPath: /optisam_dir
                - name: secret-volume
                  mountPath: /opt/secret
                  readOnly: true
                - name: secret-volume-ca
                  readOnly: true
                  mountPath: /opt/secret-ca
                - name: secret-volume-client
                  readOnly: true
                  mountPath: /opt/secret-client
                - name: secret-volume-key
                  readOnly: true
                  mountPath: /opt/secret-key

          volumes:
            - name: config-volume-${ENV}
              configMap:
                name: config-import-${ENV}
            - name: optisam-dir
              persistentVolumeClaim:
                claimName: optisam-storage
            - name: secret-volume
              secret:
                secretName: secret-apipublickey-${ENV}
            - name: secret-volume-ca
              secret:
                secretName: kafka-ca.crt-${ENV}
            - name: secret-volume-client
              secret:
                secretName: kafka-client.crt-${ENV}
            - name: secret-volume-key
              secret:
                secretName: kafka-client.key-${ENV}

parameters:
  - name: MIG_DIR
    description: Postgres Database variable
    required: true
  - name: MIG_VERSION
    description: Postgres Database variable
    required: true
  - name: TAG
    description: Tag for Docker image
    value: latest
    required: true
  - name: ENV
    description: Env for deployment
    required: true
  - name: REPLICAS
    description: Pod replica count
    value: "1"
    required: true
  - name: DOCKER_REGISTRY
    description: Artifactory URL to download images
    value: "optisam-it-virt-docker-unstable.repos.tech.orange"
    required: true
